def extend(tables):
 tables.update({
 'diem_tiep_nhan':('Điểm tiếp nhận theo hiệu lực',[
 ('id','uuid','PK','Không','Định danh điểm phục vụ'),('ma','varchar(50)','UQ','Không','Mã điểm trong danh mục'),('co_quan_id','uuid','FK co_quan','Không','Đơn vị quản lý điểm'),('ten','text','','Không','Tên điểm'),('dia_chi','text','','Không','Địa chỉ công khai'),('hieu_luc_tu','timestamptz','','Không','Bắt đầu phục vụ'),('hieu_luc_den','timestamptz','','Có','Kết thúc hoặc chuyển điểm')]),
 'mau_bao_cao':('Phiên bản mẫu và công thức báo cáo',[
 ('id','uuid','PK','Không','Định danh mẫu phiên bản'),('ma','varchar(50)','','Không','Mã mẫu'),('so_phien_ban','integer','','Không','Phiên bản công thức'),('ten','text','','Không','Tên và mục đích'),('dinh_nghia','jsonb','','Không','Tử số, mẫu số, bộ lọc và loại trừ'),('nguon_du_lieu','jsonb','','Không','Hệ thống và mốc lấy dữ liệu'),('phe_duyet_id','uuid','FK tai_khoan','Không','Người duyệt định nghĩa'),('hieu_luc_tu','timestamptz','','Không','Bắt đầu áp dụng'),('hieu_luc_den','timestamptz','','Có','Kết thúc áp dụng')]),
 'tai_lieu_huong_dan':('Nguồn hướng dẫn có phiên bản',[
 ('id','uuid','PK','Không','Định danh nguồn'),('ten','text','','Không','Tên tài liệu'),('can_cu','text','','Không','Nguồn và thẩm quyền ban hành'),('so_phien_ban','integer','','Không','Phiên bản được dùng'),('dia_chi','text','','Không','Địa chỉ hoặc khóa tài liệu'),('bam_sha256','char(64)','','Không','Toàn vẹn bản đã duyệt'),('phe_duyet_id','uuid','FK tai_khoan','Không','Người duyệt dùng hướng dẫn'),('hieu_luc_tu','timestamptz','','Không','Mốc áp dụng'),('hieu_luc_den','timestamptz','','Có','Mốc hết áp dụng'),('trang_thai','varchar(30)','','Không','Duyệt, thay thế hoặc thu hồi')]),
 'tai_lieu_kho':('Tài liệu kho của tổ chức, cá nhân',[
 ('id','uuid','PK','Không','Định danh bản tài liệu'),('chu_the_id','uuid','FK chu_the','Không','Chủ thể sở hữu quyền khai thác'),('ket_qua_id','uuid','FK ket_qua','Có','Bản kết quả nếu có'),('thanh_phan_id','uuid','FK thanh_phan_ho_so','Có','Thành phần nếu có'),('loai','varchar(100)','','Không','Loại tài liệu'),('nguon','text','','Không','Cơ quan cấp và tham chiếu nguồn'),('khoa_doi_tuong','text','','Không','Bản lưu được bảo vệ'),('bam_sha256','char(64)','','Không','Toàn vẹn bản lưu'),('hieu_luc_tu','timestamptz','','Có','Bắt đầu giá trị sử dụng nếu áp dụng'),('hieu_luc_den','timestamptz','','Có','Kết thúc giá trị sử dụng nếu áp dụng'),('thay_the_id','uuid','FK tai_lieu_kho','Có','Bản được thay thế'),('trang_thai','varchar(30)','','Không','Chờ kiểm tra, hợp lệ hoặc bị thay thế')]),
 'quyen_khai_thac_kho':('Quyền khai thác tài liệu kho',[
 ('id','uuid','PK','Không','Định danh lần cấp'),('tai_lieu_id','uuid','FK tai_lieu_kho','Không','Tài liệu được khai thác'),('chu_the_id','uuid','FK chu_the','Không','Chủ thể được phép'),('muc_dich','text','','Không','Phạm vi và mục đích'),('can_cu','text','','Không','Căn cứ quyền hoặc đại diện'),('hieu_luc_tu','timestamptz','','Không','Bắt đầu quyền'),('hieu_luc_den','timestamptz','','Có','Kết thúc quyền'),('trang_thai','varchar(30)','','Không','Có hiệu lực hoặc thu hồi')]),
 'chi_dao_dieu_hanh':('Chỉ đạo và trách nhiệm phản hồi',[
 ('id','uuid','PK','Không','Định danh nhiệm vụ'),('ho_so_id','uuid','FK ho_so','Có','Hồ sơ liên quan nếu có'),('co_quan_id','uuid','FK co_quan','Không','Phạm vi điều hành'),('nguoi_giao_id','uuid','FK tai_khoan','Không','Người ra chỉ đạo'),('nguoi_nhan_id','uuid','FK tai_khoan','Có','Người thực hiện'),('noi_dung','text','','Không','Nhiệm vụ có căn cứ'),('tao_luc','timestamptz','','Không','Thời điểm giao'),('han_phan_hoi','timestamptz','','Không','Mốc phản hồi nhiệm vụ'),('trang_thai','varchar(30)','','Không','Giao, xử lý hoặc hoàn thành'),('tham_chieu_phan_hoi','text','','Có','Bằng chứng thực hiện'),('phien_ban','integer','','Không','Kiểm soát cập nhật đồng thời')])
 })
 return tables
