from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'03_Thiet_ke/Huong_doi_tuong'; OUT.mkdir(exist_ok=True)
GROUPS={1:'Tài khoản và quyền',2:'Danh mục và quy trình',3:'Chữ ký số',4:'Tiếp nhận và giải quyết',5:'Tiện ích',6:'Thống kê và báo cáo',7:'Điều hành tác nghiệp',8:'Kho dữ liệu',9:'Tích hợp và liên thông'}
# Dữ liệu đặc tả đề xuất; mã CN giữ nguyên khung phân tích đã có.
# Tên lớp và thao tác là hợp đồng lập trình mới, không phải tên nội bộ Hà Nội.
RAW=[
(1,1,'Quản lý tài khoản','Quản trị được ủy quyền','TaiKhoan','tai_khoan,quyen_pham_vi','capQuyen','Căn cứ cấp quyền, cơ quan, vai trò, ngày hiệu lực','Người đề nghị không tự phê duyệt quyền của mình','Chọn tài khoản;Lập đề nghị cấp hoặc thu hồi quyền;Người có thẩm quyền phê duyệt;Kiểm tra quyền mới và nhật ký','Quyền chưa được duyệt hoặc hết hiệu lực không được áp dụng'),
(2,2,'Quản lý danh mục dùng chung','Quản trị nghiệp vụ','CoQuan','co_quan,diem_tiep_nhan','congBoDanhMuc','Mã, tên, loại đơn vị, thời gian hiệu lực','Mã không trùng và khoảng hiệu lực không chồng lấn','Chọn loại danh mục;Nhập mã và thời gian hiệu lực;Đối chiếu nguồn công bố;Công bố phiên bản được duyệt','Đổi tên cơ quan không làm mất cơ quan gốc của hồ sơ cũ'),
(3,2,'Công bố phiên bản thủ tục','Quản trị nghiệp vụ','PhienBanThuTuc','thu_tuc,phien_ban_thu_tuc,tuyen_xu_ly','congBoPhienBan','Mã quốc gia, quyết định, hiệu lực, mẫu, quy tắc hạn','Quyết định và tuyến xử lý đã được phê duyệt','Chọn mã thủ tục;Nhập phiên bản và căn cứ;Kiểm tra hạn và thành phần;Công bố theo ngày hiệu lực','Không sửa phiên bản đã được hồ sơ sử dụng'),
(4,2,'Cấu hình trạng thái hồ sơ','Quản trị nghiệp vụ','PhienBanThuTuc','phien_ban_thu_tuc','cauHinhTrangThai','Trạng thái nguồn, đích, sự kiện, điều kiện và quyền','Không có bước kết thúc không thể đến hoặc chuyển bước trái quyền','Chọn bản quy trình nháp;Khai báo trạng thái và sự kiện;Kiểm tra đường đi và điều kiện;Trình duyệt cấu hình','Không gộp tài chính, giao nhận và đồng bộ vào trạng thái chuyên môn'),
(5,2,'Chuẩn bị và gửi hồ sơ điện tử','Người yêu cầu','HoSo','ho_so,chu_the,uy_quyen,thanh_phan_ho_so','guiYeuCau','Phiên bản thủ tục, chủ thể, tờ khai, tài liệu, mã yêu cầu','Đúng chủ thể, đủ trường bắt buộc và đúng tuyến','Chọn thủ tục và cơ quan;Kê khai và chọn tài liệu hợp lệ;Xem lại quan hệ đại diện và dữ liệu;Gửi và lưu mã giao dịch','Mã gửi lặp trả lại kết quả cũ; thiếu kết nối giữ bản nháp'),
(6,2,'Luân chuyển hồ sơ','Cán bộ tiếp nhận','HoSo','ho_so,tuyen_xu_ly,tham_chieu_lien_thong','chuyenTuyen','Hồ sơ, nguồn, đích, căn cứ, phiên bản','Đích có thẩm quyền và xác nhận nhận đủ','Chọn hồ sơ cần chuyển;Xác định đích và căn cứ;Gửi gói bàn giao;Theo dõi xác nhận trước khi đóng trách nhiệm nguồn','Giữ hạn pháp lý và mã hồ sơ; mất phản hồi không tạo hồ sơ mới'),
(7,2,'Thực hiện bước quy trình','Chuyên viên thụ lý','HoSo','ho_so,su_kien_xu_ly,phan_cong','chuyenBuoc','Hành động, phiên bản hồ sơ, bằng chứng xử lý','Đúng phân công, đúng trạng thái và đủ dữ liệu chuyển bước','Mở công việc được giao;Đọc bước hiện hành;Bổ sung bằng chứng xử lý;Thực hiện hành động được cho phép','Phiên bản không khớp phải tải lại; không ghi đè ý kiến'),
(8,2,'Theo dõi tiến trình hồ sơ','Người yêu cầu','HoSo','ho_so,su_kien_xu_ly','xemTienTrinh','Mã hồ sơ và quan hệ truy cập','Chủ thể có quyền xem hồ sơ này','Nhập hoặc chọn mã hồ sơ;Xác nhận quan hệ truy cập;Xem mốc xử lý và hạn;Đọc thông báo cần thực hiện','Chỉ hiển thị phần được công khai; không lộ ý kiến nội bộ'),
(9,2,'Thiết kế quy trình trực quan','Quản trị nghiệp vụ','PhienBanThuTuc','phien_ban_thu_tuc','kiemTraDoThi','Bước, cạnh, vai trò, điều kiện, thời hạn','Đồ thị hợp lệ, mọi nhánh có lối ra được xác định','Tạo bản nháp quy trình;Nối bước và khai báo điều kiện;Chạy kiểm tra cấu trúc;Trình duyệt trước khi áp dụng','Nhánh song song phải có quy tắc tổng hợp; không tự đổi hồ sơ đang xử lý'),
(10,3,'Ký kết quả theo thẩm quyền','Lãnh đạo có thẩm quyền','KetQua','ket_qua,chu_ky','kyBanDuThao','Mã dự thảo, phiên bản, giá trị băm, chứng thư','Dự thảo được duyệt, chứng thư phù hợp và còn giá trị','Chọn đúng bản dự thảo;Đọc toàn bộ nội dung cần ký;Xác nhận ký trên phương tiện được cấp;Kiểm tra chữ ký trên chính tệp đã nhận','Tệp thay đổi hoặc chứng thư không đạt thì không chuyển sang đã ký'),
(11,3,'Kết nối dịch vụ ký','Quản trị tích hợp','HeThongKetNoi','he_thong_ket_noi,chu_ky','kiemTraKetNoiKy','Nguồn ký, cấu hình xác thực, mã tương quan','Đúng hợp đồng và môi trường đã được cấp phép','Chọn dịch vụ ký;Khai báo cấu hình trong kho bí mật;Thử bằng tài liệu thử được phép;Đối chiếu phiên bản và kết quả ký','Không ghi khóa bí mật vào hồ sơ hoặc nhật ký; chưa phản hồi không là ký thành công'),
(12,4,'Kiểm tra và tiếp nhận hồ sơ','Cán bộ tiếp nhận','HoSo','ho_so,phien_ban_thu_tuc,lich_lam_viec','tiepNhan','Hồ sơ chờ nhận, thành phần, thẩm quyền, lịch','Đủ điều kiện theo phiên bản thủ tục đang áp dụng','Mở hồ sơ chờ tiếp nhận;Kiểm tra chủ thể và thành phần;Chọn nhận hoặc thông báo thiếu có căn cứ;Cấp mã chính thức và giấy hẹn','Yêu cầu bổ sung khác từ chối; mốc 15 giờ chỉ áp dụng thủ tục có quy định'),
(13,4,'Yêu cầu và nhận bổ sung','Cán bộ tiếp nhận','YeuCauBoSung','ho_so,yeu_cau_bo_sung,thanh_phan_ho_so','ghiNhanBoSung','Hồ sơ, giai đoạn, nội dung thiếu, căn cứ, phản hồi','Bổ sung được đối chiếu với đúng yêu cầu còn mở','Chỉ rõ nội dung và căn cứ cần bổ sung;Gửi yêu cầu cho đúng người;Người yêu cầu gửi tài liệu;Kiểm tra và quay lại giai đoạn đã lưu','Bổ sung không tự làm lại hạn; lưu giai đoạn tiếp nhận hoặc thẩm định'),
(14,4,'Phân công xử lý','Lãnh đạo đơn vị','PhanCong','ho_so,phan_cong,tai_khoan','giaoNhiemVu','Hồ sơ, người nhận, phạm vi, phiên bản','Người nhận còn quyền và hồ sơ chưa kết thúc','Chọn hồ sơ đã nhận;Chọn người có thẩm quyền;Ghi trách nhiệm và căn cứ;Xác nhận phân công hiện hành','Kết thúc phân công cũ và tạo phân công mới trong cùng giao dịch'),
(15,4,'Thẩm định và phối hợp','Chuyên viên thụ lý','NhiemVuPhoiHop','ho_so,nhiem_vu_phoi_hop,ket_qua','tongHopYKien','Bằng chứng nguồn, ý kiến, dự thảo, nhiệm vụ','Đủ ý kiến bắt buộc hoặc có căn cứ xử lý thay thế','Đối chiếu dữ liệu chuyên ngành;Giao nhiệm vụ khi cần phối hợp;Kiểm tra ý kiến đã xác nhận;Lập dự thảo và trình duyệt','Không dùng phản hồi lỗi như dữ liệu âm tính; ý kiến thay đổi phải tăng phiên bản'),
(16,4,'Phê duyệt và phát hành','Lãnh đạo có thẩm quyền','KetQua','ket_qua,chu_ky,ho_so,hang_doi_gui','phatHanh','Dự thảo, ý kiến, chữ ký, số văn bản','Đúng thẩm quyền, chữ ký hợp lệ và đủ căn cứ','Đọc dự thảo và căn cứ;Phê duyệt hoặc trả chỉnh sửa;Văn thư kiểm tra và cấp số;Phát hành bản bất biến cùng thông điệp gửi','Phê duyệt khác phát hành; không sửa tệp đã ký để thêm nội dung'),
(17,4,'Dừng giải quyết theo căn cứ','Lãnh đạo có thẩm quyền','HoSo','ho_so,su_kien_xu_ly,khoan_thu','dungGiaiQuyet','Đề nghị dừng, căn cứ, người duyệt, nghĩa vụ còn lại','Không dừng hồ sơ đã kết thúc bằng thao tác thông thường','Mở đề nghị dừng;Kiểm tra căn cứ và tác động;Phê duyệt quyết định dừng;Thông báo và xử lý nghĩa vụ tài chính','Yêu cầu rút của công dân chưa đồng nghĩa đã có quyết định dừng'),
(18,4,'Giao và xác nhận kết quả','Cán bộ trả kết quả','GiaoNhan','ket_qua,giao_nhan,chu_the','xacNhanGiao','Bản phát hành, người nhận, kênh và chứng cứ','Người nhận có quyền, kết quả đã phát hành','Chọn kết quả chính thức;Xác minh người nhận hoặc địa chỉ kho;Thực hiện giao và lấy bằng chứng;Xác nhận giao hoặc ghi lỗi giao','Gửi thông báo không chứng minh người nhận đã nhận kết quả'),
(19,5,'In và kết xuất tài liệu','Cán bộ tiếp nhận','HoSo','ho_so,ket_qua','ketXuatTaiLieu','Mã hồ sơ, mẫu, phiên bản và mục đích','Có quyền kết xuất và dùng đúng mẫu','Chọn chứng từ cần in;Kiểm tra phiên bản và dữ liệu;Xem trước bố cục;In hoặc tải bản được phép','Bản dự thảo phải phân biệt bản chính thức; ghi nhật ký kết xuất'),
(20,5,'Gửi thông báo và nhắc việc','Cán bộ được giao','ThongBao','thong_bao,ho_so','lapThongBao','Sự kiện, người nhận, nội dung, kênh','Đúng người nhận, đúng mục đích và mức công khai','Chọn sự kiện hoặc lịch nhắc;Kiểm tra người nhận;Gửi qua kênh đã xác nhận;Theo dõi gửi thành công hoặc lỗi','Không đưa dữ liệu nhạy cảm vào tin nhắn; thử lại giữ mã thông báo'),
(21,5,'Tra cứu theo phạm vi','Người được cấp quyền','HoSo','ho_so,ket_qua','timKiemCoQuyen','Từ khóa, bộ lọc, mục đích, trang kết quả','Phạm vi quyền được áp dụng trước khi trả kết quả','Nhập từ khóa và bộ lọc;Chọn phạm vi được giao;Xem kết quả đã lọc quyền;Mở hồ sơ hoặc kết xuất khi có quyền','Không cho suy ra hồ sơ ngoài quyền từ tổng số hoặc gợi ý tìm kiếm'),
(22,5,'Tra cứu hướng dẫn cho cán bộ','Cán bộ được giao','TaiLieuHuongDan','tai_lieu_huong_dan','traCuuCanCu','Câu hỏi, thủ tục và ngày áp dụng','Tài liệu còn hiệu lực và có nguồn kiểm chứng','Chọn thủ tục và thời điểm;Nhập vấn đề cần hỗ trợ;Đọc hướng dẫn kèm nguồn;Đối chiếu trước khi đưa ra quyết định','Nguồn hết hiệu lực phải cảnh báo; trợ giúp không tự phê duyệt hồ sơ'),
(23,6,'Tổng hợp báo cáo theo kỳ','Người giám sát','MauBaoCao','mau_bao_cao,ho_so','tongHopBaoCao','Mẫu, kỳ, cơ quan, thời điểm chốt','Mẫu được duyệt và dữ liệu thuộc phạm vi được giao','Chọn mẫu và kỳ;Chốt nguồn dữ liệu;Kiểm tra tổng và ngoại lệ;Kết xuất báo cáo có dấu thời điểm','Số liệu địa phương và bộ phải khử trùng; không cộng số khác kỳ'),
(24,6,'Quản lý mẫu báo cáo','Quản trị nghiệp vụ','MauBaoCao','mau_bao_cao','congBoMauBaoCao','Cột, công thức, bộ lọc, hiệu lực','Công thức có mẫu đối chiếu và người phê duyệt','Tạo phiên bản mẫu;Khai báo công thức và điều kiện loại trừ;Đối chiếu dữ liệu mẫu;Phê duyệt và công bố','Không thay công thức ngầm trong báo cáo đã chốt'),
(25,6,'Thống kê hồ sơ','Người giám sát','HoSo','ho_so,tham_chieu_lien_thong','thongKeHoSo','Chiều phân tích, phạm vi, kỳ, mốc nguồn','Tập hồ sơ chuẩn và quy tắc mẫu số đã được xác định','Chọn chỉ tiêu cần thống kê;Chọn cơ quan và thời gian;Đọc công thức và ngoại lệ;Đối chiếu hồ sơ tạo nên kết quả','Hiển thị dữ liệu chậm cập nhật; không suy chỉ tiêu hoàn thành từ lỗi đồng bộ'),
(26,7,'Theo dõi và truy vấn điều hành','Lãnh đạo đơn vị','HoSo','ho_so,phan_cong,lich_lam_viec','truyVanDieuHanh','Trách nhiệm, hạn, trạng thái và phạm vi','Chỉ truy vấn đơn vị được giao quản lý','Chọn đơn vị và mốc theo dõi;Lọc hồ sơ sắp hạn hoặc quá hạn;Xem người chịu trách nhiệm;Giao việc theo thẩm quyền','Quá hạn là chiều tính toán; cảnh báo không tự dừng hạn pháp lý'),
(27,7,'Ban hành chỉ đạo xử lý','Lãnh đạo đơn vị','ChiDaoDieuHanh','chi_dao_dieu_hanh,ho_so','banHanhChiDao','Nội dung, nơi nhận, hạn và hồ sơ liên quan','Người chỉ đạo có quyền và nơi nhận được xác định','Lập chỉ đạo;Xác định trách nhiệm và hạn báo cáo;Gửi và theo dõi tiếp nhận;Đánh giá phản hồi và kết thúc','Chỉ đạo không thay thế quyết định giải quyết của người có thẩm quyền'),
(28,8,'Quản trị tài liệu trong kho','Quản trị kho được giao','TaiLieuKho','tai_lieu_kho,quyen_khai_thac_kho','capQuyenKho','Chủ thể, tài liệu, nguồn, phiên bản, quyền','Đúng chủ sở hữu, căn cứ quyền và hạn bảo quản','Kiểm tra nguồn tài liệu;Phân loại và ghi hiệu lực;Cấp hoặc thu hồi quyền;Theo dõi phiên bản bị thay thế','Không cho quản trị kỹ thuật mặc nhiên đọc kho của mọi công dân'),
(29,8,'Tái sử dụng tài liệu trong kho','Người yêu cầu','TaiLieuKho','tai_lieu_kho,thanh_phan_ho_so','dungLaiTaiLieu','Hồ sơ đích, tài liệu, mục đích sử dụng','Tài liệu hợp lệ, đúng chủ thể và phù hợp thủ tục đích','Chọn hồ sơ đang kê khai;Chọn tài liệu được phép dùng;Đối chiếu hiệu lực và nội dung;Gắn tham chiếu nguồn vào thành phần','Tệp đã bị thay thế hoặc thu hồi quyền không được tự coi là hợp lệ'),
(30,9,'Nhận sự kiện từ hệ thống kết nối','Hệ thống đối tác','ThongDiepNhan','thong_diep_nhan,tham_chieu_lien_thong,he_thong_ket_noi','nhanSuKien','Nguồn, mã sự kiện, thứ tự, chữ ký, nội dung','Nguồn hợp lệ, đúng hợp đồng và không sai thứ tự','Xác nhận hợp đồng và danh tính nguồn;Tiếp nhận thông điệp;Kiểm tra trùng và thứ tự;Áp dụng sự kiện hoặc đưa vào đối soát','Cùng mã khác nội dung bị cách ly; sự kiện cũ không ghi lùi trạng thái'),
(31,9,'Trao đổi với cổng quốc gia','Tiến trình tích hợp','HangDoiGui','hang_doi_gui,ho_so,tham_chieu_lien_thong','guiThongDiep','Đích nhận, mã tương quan, hồ sơ, phiên bản','Thông điệp được tạo từ giao dịch nghiệp vụ đã lưu','Lấy thông điệp đến hạn gửi;Gửi cùng mã tương quan;Đọc biên nhận theo hợp đồng;Xác nhận thành công hoặc lập lịch thử lại','Mất phản hồi không tạo hồ sơ mới; chưa áp dụng khác đã nhận thông điệp'),
(32,4,'Thanh toán khoản thu','Người yêu cầu','KhoanThu','khoan_thu,giao_dich','taoGiaoDichThu','Khoản thu còn nợ, số tiền, căn cứ miễn giảm','Khoản thu thực sự áp dụng và đúng người trả','Kiểm tra thông báo thu;Chọn phương thức được hỗ trợ;Xác nhận tại đơn vị thanh toán;Theo dõi giao dịch và chứng từ','Thủ tục không thu phí bỏ qua; không dùng ảnh màn hình thay đối soát'),
(33,6,'Đối soát thu và hoàn','Cán bộ tài chính','GiaoDich','giao_dich,khoan_thu','doiSoat','Mã đối tác, giao dịch, tiền, trạng thái, kỳ','Thông báo được xác thực và mã giao dịch duy nhất','Lấy số liệu đối tác theo kỳ;Ghép mã giao dịch và khoản thu;Xử lý chênh lệch có căn cứ;Chốt đối soát hoặc đề nghị hoàn','Thông báo lặp không cộng tiền; giao dịch hoàn cần phê duyệt riêng'),
(34,4,'Số hóa hồ sơ giấy','Cán bộ tiếp nhận','ThanhPhanHoSo','thanh_phan_ho_so,ho_so','xacNhanSoHoa','Tệp, số trang, loại, nguồn và người đối chiếu','Đọc được, đầy đủ, đúng hồ sơ và đúng quy định xác nhận','Chọn thành phần cần số hóa;Quét đủ trang và kiểm tra hình ảnh;Đối chiếu với giấy được xuất trình;Lưu phiên bản và bằng chứng xác nhận','Tệp mờ hoặc thiếu trang phải làm lại; không xác nhận thay người có thẩm quyền'),
(35,5,'Gửi phản ánh và đánh giá','Người yêu cầu','PhanAnh','phan_anh,ho_so','guiPhanAnh','Loại phản ánh, nội dung, liên hệ, hồ sơ nếu có','Đúng kênh, không trùng yêu cầu cùng nội dung','Chọn loại phản ánh hoặc đánh giá;Nhập nội dung và tài liệu cần thiết;Gửi và lưu mã theo dõi;Đọc trả lời hoặc yêu cầu bổ sung','Phản ánh không tự sửa quyết định hồ sơ; khiếu nại dùng quy trình pháp lý riêng'),
(36,8,'Lập gói và nộp lưu hồ sơ','Cán bộ lưu trữ','HoSoNopLuu','ho_so_nop_luu,dot_nop_luu,ho_so','nopLuu','Danh mục tệp, phiên bản, giá trị băm, thời hạn giữ','Hồ sơ kết thúc và đủ thành phần được duyệt','Chốt hồ sơ và phiên bản;Lập danh mục gói nộp lưu;Kiểm tra đủ tệp và toàn vẹn;Gửi gói và lưu biên nhận','Kho công dân khác lưu trữ cơ quan; bị trả gói phải bổ sung đúng phiên bản'),
]
READ={8,21,22,23,25,26}
MODEL=[]
for n,g,name,actor,entity,tables,op,inp,guard,steps,exception in RAW:
 MODEL.append(dict(id=f'UC{n:02}',function=f'CN{n:02}' if n<=31 else f'MR{n-31:02}',group=g,name=name,actor=actor,entity=entity,tables=[('phan_anh_kien_nghi' if t=='phan_anh' else t) for t in tables.split(',')],operation=op,inputs=inp,guard=guard,steps=steps.split(';'),exception=exception,read_only=n in READ,screen=f'MH{n:02}',test=f'OO{n:02}',controller=f'DieuKhien{entity}',route=f'/nghien-cuu/chuc-nang/{n:02}',status='Thiết kế đề xuất'))
(OUT/'Danh_muc_ca_su_dung.json').write_text(json.dumps(MODEL,ensure_ascii=False,indent=2),encoding='utf-8')
assert len(MODEL)==36 and len({x['id'] for x in MODEL})==36
