"""Nội dung nghiệp vụ được biên tập theo từng Use case, ngày 03/10/2026."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
MODEL=json.loads((ROOT/'03_Thiet_ke/Huong_doi_tuong/Danh_muc_ca_su_dung.json').read_text('utf-8'))
DATA={}
def add(n,purpose,pre,steps,post,exception,explain,guard,error,labels,messages):
 u=next(x for x in MODEL if x['id']==f'UC{n:02}')
 DATA[u['id']]={**u,'purpose':purpose,'pre':pre,'steps':steps.split('|'),'post':post,'exception':exception,'explain':explain,'guard_short':guard,'error_short':error,'labels':labels.split('|'),'messages':messages.split('|')}

add(1,'Cấp, thay đổi hoặc thu hồi quyền làm việc của một tài khoản cán bộ.',
 'Người quản trị đã đăng nhập và được giao quản lý tài khoản của cơ quan. Người duyệt quyền phải khác người đề nghị.',
 'Người quản trị chọn tài khoản cần thay đổi.|Người quản trị khai báo vai trò, cơ quan, thời gian áp dụng và căn cứ cấp quyền.|Người có thẩm quyền duyệt đề nghị.|Hệ thống áp dụng quyền đã được duyệt và ghi lại người thực hiện.',
 'Tài khoản có quyền mới trong thời gian được duyệt; lịch sử quyền cũ được giữ lại.',
 'Hệ thống không cấp quyền khi đề nghị chưa được duyệt hoặc thời gian áp dụng đã hết. Nếu người quản trị chọn chính mình làm người duyệt, hệ thống yêu cầu đổi người duyệt.',
 'Quyền của cán bộ phải gắn với công việc và cơ quan được giao. Chẳng hạn, cán bộ tiếp nhận của một cơ quan chỉ được xem và tiếp nhận hồ sơ thuộc cơ quan đó. Khi cán bộ chuyển công tác, người quản trị thu hồi quyền cũ rồi đề nghị quyền tại cơ quan mới; việc chuyển công tác không làm mất lịch sử xử lý hồ sơ.',
 'Đề nghị đã được duyệt','Chưa được duyệt','Quản trị\nđược giao|Quản lý\ntài khoản|Xử lý\nphân quyền|Tài khoản\nvà quyền',
 'Chọn tài khoản và quyền|Gửi đề nghị cấp quyền|Kiểm tra người duyệt|Đề nghị đã được duyệt|Áp dụng quyền đã duyệt|Đã lưu quyền mới|Trả danh sách quyền|Hiển thị quyền được cấp')
add(2,'Quản lý danh mục cơ quan, điểm tiếp nhận và các mã dùng chung của hệ thống.',
 'Người quản trị được giao cập nhật danh mục và có văn bản làm căn cứ cho nội dung thay đổi.',
 'Người quản trị chọn danh mục cơ quan hoặc điểm tiếp nhận.|Người quản trị nhập mã, tên và thời gian áp dụng.|Hệ thống kiểm tra mã trùng và thời gian áp dụng của các bản ghi.|Người quản trị công bố nội dung đã được duyệt.',
 'Danh mục mới được sử dụng từ ngày có hiệu lực; hồ sơ cũ vẫn lưu thông tin cơ quan tại thời điểm tiếp nhận.',
 'Nếu mã đã tồn tại hoặc thời gian áp dụng bị trùng, hệ thống chỉ rõ bản ghi cần sửa. Việc đổi tên cơ quan không được xóa thông tin cơ quan trong hồ sơ đã tiếp nhận.',
 'Danh mục dùng chung giúp tên cơ quan và điểm tiếp nhận được sử dụng thống nhất khi nộp, chuyển và tra cứu hồ sơ. Khi một đơn vị đổi tên, hệ thống lưu tên mới kèm ngày bắt đầu áp dụng. Nhờ vậy, người tra cứu vẫn biết hồ sơ cũ do đơn vị nào tiếp nhận, thay vì chỉ thấy tên hiện tại.',
 'Mã và thời gian hợp lệ','Trùng mã hoặc thời gian','Quản trị\nnghiệp vụ|Quản lý\ndanh mục|Xử lý\ndanh mục|Danh mục\ncơ quan',
 'Nhập cơ quan và hiệu lực|Gửi nội dung danh mục|Tìm mã và thời gian trùng|Kết quả đối chiếu mã|Lưu danh mục được duyệt|Đã lưu danh mục|Trả danh mục mới|Hiển thị cơ quan mới')
add(3,'Đưa một phiên bản thủ tục đã được phê duyệt vào sử dụng.',
 'Quyết định công bố thủ tục, cơ quan giải quyết và quy trình xử lý đã được người có thẩm quyền phê duyệt.',
 'Người quản trị chọn mã thủ tục hành chính.|Người quản trị nhập quyết định, thành phần hồ sơ, biểu mẫu, thời hạn và cơ quan giải quyết.|Hệ thống kiểm tra nội dung bắt buộc và ngày áp dụng.|Người quản trị công bố phiên bản đã được duyệt.',
 'Phiên bản mới được dùng đúng ngày có hiệu lực. Hồ sơ đã tiếp nhận vẫn gắn với phiên bản áp dụng trước đó.',
 'Hệ thống không công bố khi thiếu quyết định hoặc chưa có quy trình được duyệt. Phiên bản đã được hồ sơ sử dụng phải được giữ nguyên; nội dung thay đổi được lập thành phiên bản mới.',
 'Một thủ tục có thể thay đổi biểu mẫu, thời hạn hoặc cơ quan giải quyết qua từng quyết định. Vì vậy, hệ thống cần lưu từng phiên bản thay vì sửa trực tiếp bản đang dùng. Khi tra cứu một hồ sơ, cán bộ có thể xác định được các yêu cầu đã áp dụng tại thời điểm tiếp nhận hồ sơ đó.',
 'Đủ căn cứ công bố','Thiếu căn cứ công bố','Quản trị\nnghiệp vụ|Công bố\nthủ tục|Xử lý\nthủ tục|Phiên bản\nthủ tục',
 'Chọn thủ tục cần công bố|Gửi phiên bản mới|Kiểm tra quyết định và hiệu lực|Kết quả kiểm tra phiên bản|Lưu và công bố phiên bản|Đã công bố phiên bản|Trả ngày bắt đầu áp dụng|Hiển thị thủ tục đã công bố')
add(4,'Khai báo các trạng thái của hồ sơ và điều kiện chuyển từ bước này sang bước khác.',
 'Người quản trị được phép sửa bản nháp quy trình. Quy trình đang áp dụng cho hồ sơ thật không bị sửa trực tiếp.',
 'Người quản trị mở bản nháp quy trình của một thủ tục.|Người quản trị khai báo các bước, trạng thái hồ sơ và vai trò được xử lý tại từng bước.|Hệ thống kiểm tra bước bị bỏ rơi, nhánh không có điểm kết thúc và quyền chuyển bước.|Người quản trị sửa các lỗi được chỉ ra rồi lưu bản nháp để trình duyệt.',
 'Bản nháp quy trình được lưu cùng kết quả kiểm tra. Chỉ phiên bản được phê duyệt mới được đưa vào sử dụng.',
 'Nếu một bước không có đường đi đến kết thúc hoặc chưa được giao vai trò xử lý, hệ thống đánh dấu bước đó và yêu cầu sửa. Trạng thái thanh toán, giao kết quả và đồng bộ được quản lý riêng với trạng thái xử lý hồ sơ.',
 'UC04 trả lời hai câu hỏi: hồ sơ đang ở bước nào và ai được đưa hồ sơ sang bước tiếp theo. Ví dụ, hồ sơ đang thẩm định chỉ được trình duyệt sau khi chuyên viên đã lập dự thảo và thu đủ ý kiến bắt buộc. Người quản trị khai báo quy tắc này trên bản nháp; cán bộ xử lý hồ sơ không được tự bỏ qua bước đã quy định.',
 'Quy trình không có lỗi','Quy trình còn lỗi','Quản trị\nnghiệp vụ|Cấu hình\nquy trình|Kiểm tra\nquy trình|Quy trình\nthủ tục',
 'Khai báo bước và vai trò|Gửi bản nháp kiểm tra|Kiểm tra đường đi và quyền|Danh sách lỗi quy trình|Lưu bản nháp hợp lệ|Đã lưu bản nháp|Trả kết quả để trình duyệt|Hiển thị bản nháp đã lưu')
add(5,'Cho phép người dân hoặc tổ chức kê khai và gửi hồ sơ qua mạng.',
 'Người nộp đã xác thực tài khoản. Thủ tục và cơ quan được chọn cho phép nộp trực tuyến; người nộp có quyền nộp cho bản thân hoặc đại diện.',
 'Người nộp chọn thủ tục và cơ quan có thẩm quyền.|Người nộp điền tờ khai, đính kèm tài liệu và khai báo thông tin đại diện nếu có.|Hệ thống kiểm tra trường bắt buộc, tệp đính kèm và cơ quan tiếp nhận.|Người nộp xem lại nội dung, xác nhận gửi và lưu mã theo dõi.',
 'Hồ sơ chuyển từ bản nháp sang chờ tiếp nhận và có mã theo dõi để người nộp tra cứu.',
 'Nếu thiếu thông tin, hệ thống chỉ rõ trường cần bổ sung và giữ bản nháp. Nếu người nộp bấm gửi nhiều lần, hệ thống trả lại cùng mã hồ sơ, không tạo các hồ sơ trùng nhau.',
 'Gửi hồ sơ trực tuyến chưa có nghĩa là hồ sơ đã được cơ quan tiếp nhận chính thức. Sau khi gửi, người nộp dùng mã theo dõi để xem cán bộ đã nhận hồ sơ hay yêu cầu bổ sung. Chức năng này cần giữ lại bản nháp khi mất kết nối để người dùng không phải kê khai lại từ đầu.',
 'Hồ sơ đủ thông tin','Thiếu thông tin bắt buộc','Người nộp\nhồ sơ|Nộp hồ sơ\ntrực tuyến|Xử lý\nhồ sơ gửi|Hồ sơ\nđiện tử',
 'Kê khai và đính kèm tệp|Gửi hồ sơ đã xác nhận|Kiểm tra tờ khai và người nộp|Kết quả kiểm tra hồ sơ|Lưu hồ sơ chờ tiếp nhận|Mã theo dõi hồ sơ|Trả xác nhận đã gửi|Hiển thị mã theo dõi')
add(6,'Chuyển hồ sơ đến cơ quan có trách nhiệm xử lý và theo dõi việc nhận bàn giao.',
 'Hồ sơ còn đang xử lý. Cán bộ được phép chuyển hồ sơ và cơ quan nhận được xác định theo quy trình của thủ tục.',
 'Cán bộ chọn hồ sơ cần chuyển.|Cán bộ chọn cơ quan nhận và nêu căn cứ chuyển.|Hệ thống gửi hồ sơ cùng tài liệu và thông tin thời hạn.|Cơ quan nhận xác nhận bàn giao; hệ thống cập nhật cơ quan đang chịu trách nhiệm.',
 'Hồ sơ ghi nhận cơ quan nhận và thời điểm bàn giao. Mã hồ sơ và lịch sử xử lý được giữ nguyên.',
 'Nếu chưa có xác nhận từ cơ quan nhận, cơ quan gửi vẫn phải theo dõi hồ sơ. Mất phản hồi không được tạo hồ sơ mới hoặc tự đặt lại thời hạn giải quyết.',
 'Luân chuyển cần theo dõi cả việc gửi và việc nhận. Một hồ sơ chỉ được coi là bàn giao xong khi cơ quan nhận đã xác nhận đủ dữ liệu cần xử lý. Thiết kế này giúp xác định trách nhiệm khi hồ sơ đi qua nhiều cơ quan, đặc biệt khi kết nối giữa các hệ thống bị gián đoạn.',
 'Cơ quan nhận đã xác nhận','Chưa có xác nhận bàn giao','Cán bộ\ntiếp nhận|Chuyển\nhồ sơ|Theo dõi\nbàn giao|Thông tin\nluân chuyển',
 'Chọn cơ quan nhận hồ sơ|Gửi yêu cầu bàn giao|Kiểm tra tuyến và tài liệu|Kết quả kiểm tra bàn giao|Lưu xác nhận cơ quan nhận|Đã ghi nhận cơ quan nhận|Trả tình trạng bàn giao|Hiển thị nơi đang xử lý')
add(7,'Cho phép chuyên viên hoàn thành công việc được giao và chuyển hồ sơ sang bước tiếp theo.',
 'Chuyên viên được phân công xử lý hồ sơ và hồ sơ đang ở bước mà chuyên viên có quyền thực hiện.',
 'Chuyên viên mở công việc được giao.|Chuyên viên đọc hồ sơ và yêu cầu của bước xử lý.|Chuyên viên nhập kết quả, ý kiến và tài liệu làm căn cứ.|Hệ thống kiểm tra điều kiện rồi cập nhật bước xử lý tiếp theo.',
 'Hồ sơ có trạng thái mới; ý kiến, người thực hiện và thời điểm chuyển bước được lưu lại.',
 'Nếu người khác đã cập nhật hồ sơ trong lúc chuyên viên đang xử lý, hệ thống yêu cầu tải lại dữ liệu trước khi lưu. Ý kiến cũ không bị ghi đè.',
 'Mỗi lần chuyển bước phải gắn với một công việc cụ thể. Ví dụ, chuyên viên không thể chọn trình duyệt khi chưa có dự thảo kết quả. Hệ thống chỉ hiển thị các hành động phù hợp với vai trò và trạng thái hiện tại, đồng thời kiểm tra lại điều kiện trên máy chủ khi nhận yêu cầu.',
 'Đủ điều kiện chuyển bước','Chưa đủ điều kiện','Chuyên viên\nthụ lý|Công việc\nđược giao|Xử lý\nchuyển bước|Hồ sơ\nđang xử lý',
 'Nhập ý kiến và tài liệu|Gửi yêu cầu chuyển bước|Kiểm tra phân công và bước hiện tại|Kết quả kiểm tra chuyển bước|Lưu bước xử lý mới|Đã cập nhật bước xử lý|Trả công việc tiếp theo|Hiển thị trạng thái hồ sơ')
add(8,'Giúp người nộp biết hồ sơ đang được xử lý đến đâu và cần thực hiện việc gì tiếp theo.',
 'Người tra cứu đã xác thực và có quyền xem hồ sơ được chọn.',
 'Người nộp chọn hồ sơ hoặc nhập mã theo dõi.|Hệ thống kiểm tra quyền xem hồ sơ.|Hệ thống lấy các mốc xử lý, thời hạn và thông báo được phép công khai.|Người nộp đọc tình trạng hồ sơ và yêu cầu cần thực hiện.',
 'Người nộp xem được tiến độ và thông báo của hồ sơ; việc tra cứu không thay đổi trạng thái hồ sơ.',
 'Hệ thống không hiển thị hồ sơ của người khác hoặc ý kiến xử lý nội bộ. Nếu không tìm thấy hồ sơ trong phạm vi được phép xem, hệ thống thông báo không có kết quả phù hợp.',
 'Thông tin tiến độ cần diễn đạt bằng việc đã thực hiện, chẳng hạn hồ sơ đã được tiếp nhận, đang thẩm định hoặc đang chờ người nộp bổ sung. Nếu có yêu cầu bổ sung, người nộp phải đọc được nội dung cần bổ sung và cách gửi lại tài liệu, thay vì chỉ thấy một mã trạng thái.',
 'Có quyền xem hồ sơ','Không có quyền xem','Người nộp\nhồ sơ|Tra cứu\ntiến độ|Xử lý\ntra cứu|Lịch sử\nxử lý hồ sơ',
 'Chọn mã hồ sơ cần xem|Yêu cầu xem tiến độ|Kiểm tra quyền xem hồ sơ|Kết quả kiểm tra quyền|Đọc mốc xử lý được công khai|Các mốc và thông báo|Trả tiến độ hồ sơ|Hiển thị việc cần thực hiện')
add(9,'Thiết kế các bước xử lý và các nhánh của một thủ tục trên sơ đồ trực quan.',
 'Người quản trị có quyền thiết kế quy trình và đang làm việc trên một bản nháp.',
 'Người quản trị thêm các bước tiếp nhận, thẩm định, phê duyệt và trả kết quả.|Người quản trị nối các bước, khai báo vai trò, thời hạn và điều kiện rẽ nhánh.|Hệ thống kiểm tra bước không có đường vào hoặc đường ra và các nhánh xử lý đồng thời.|Người quản trị sửa lỗi, lưu bản nháp và chuyển người có thẩm quyền xem xét.',
 'Bản nháp quy trình được lưu với các bước và điều kiện đầy đủ để trình duyệt.',
 'Nhánh xử lý đồng thời phải xác định khi nào được tổng hợp kết quả. Lưu bản nháp không làm thay đổi quy trình của hồ sơ đang xử lý.',
 'UC09 tập trung vào việc dựng và nối các bước trên sơ đồ, còn UC04 khai báo trạng thái và quyền chuyển bước. Hai chức năng cùng phục vụ thiết kế một quy trình thủ tục. Quy trình chỉ được công bố sau khi đã kiểm tra và được phê duyệt; người quản trị không áp dụng bản nháp trực tiếp cho hồ sơ của người dân.',
 'Các nhánh có đường kết thúc','Còn bước hoặc nhánh lỗi','Quản trị\nnghiệp vụ|Thiết kế\nquy trình|Kiểm tra\nsơ đồ|Bản nháp\nquy trình',
 'Thêm bước và nối nhánh|Gửi sơ đồ cần kiểm tra|Kiểm tra bước và nhánh song song|Danh sách lỗi trên sơ đồ|Lưu sơ đồ đã kiểm tra|Đã lưu sơ đồ quy trình|Trả bản nháp để trình duyệt|Hiển thị sơ đồ đã lưu')
add(10,'Ký số đúng bản dự thảo kết quả đã được phê duyệt.',
 'Người ký có thẩm quyền, dự thảo đã được duyệt và phương tiện ký được cấp còn sử dụng được.',
 'Người ký chọn bản dự thảo cần ký.|Người ký đọc nội dung và xác nhận đúng phiên bản.|Hệ thống chuyển yêu cầu đến dịch vụ ký; người ký xác nhận trên phương tiện được cấp.|Hệ thống kiểm tra chữ ký trên tệp nhận lại rồi lưu bản đã ký.',
 'Kết quả có tệp đã ký và thông tin kiểm tra chữ ký. Tệp đã ký được giữ nguyên nội dung.',
 'Nếu tệp bị thay đổi hoặc chữ ký không hợp lệ, hệ thống báo lỗi và giữ nguyên trạng thái chưa ký. Việc gửi yêu cầu ký chưa đủ để ghi nhận ký thành công.',
 'Chữ ký số phải gắn với chính tệp kết quả được phê duyệt. Sau khi ký, không được sửa nội dung tệp để bổ sung thông tin rồi tiếp tục coi chữ ký cũ là hợp lệ. Khi cần sửa kết quả, cán bộ phải lập bản mới và thực hiện lại việc duyệt, ký theo thẩm quyền.',
 'Chữ ký trên tệp hợp lệ','Ký lỗi hoặc tệp thay đổi','Người có\nthẩm quyền ký|Ký kết quả|Xử lý\nchữ ký|Bản kết quả\nvà chữ ký',
 'Chọn và xác nhận bản cần ký|Gửi yêu cầu ký số|Đọc bản đã được duyệt|Tệp và thông tin người ký|Lưu tệp có chữ ký hợp lệ|Đã lưu bản kết quả đã ký|Trả kết quả kiểm tra chữ ký|Hiển thị bản đã ký')
add(11,'Thiết lập và kiểm tra kết nối với dịch vụ ký số được phép sử dụng.',
 'Người quản trị được giao quản lý kết nối và đã có thông tin kết nối do đơn vị cung cấp dịch vụ ký cấp.',
 'Người quản trị chọn dịch vụ ký và môi trường kiểm tra.|Người quản trị khai báo địa chỉ kết nối và thông tin xác thực trong nơi lưu trữ được bảo vệ.|Hệ thống gửi tài liệu thử được phép sử dụng.|Người quản trị đối chiếu phản hồi và kiểm tra chữ ký trên tài liệu thử.',
 'Kết quả thử kết nối được ghi lại; cấu hình đạt yêu cầu được chuyển bước xét duyệt trước khi sử dụng.',
 'Nếu dịch vụ không phản hồi hoặc chữ ký thử không hợp lệ, cấu hình chưa được đưa vào dùng. Khóa bí mật và thông tin xác thực không được ghi vào hồ sơ hoặc nhật ký thông thường.',
 'Chức năng này phục vụ người quản trị kết nối, không phải người ký văn bản. Kết nối hoạt động chỉ cho biết hệ thống có thể trao đổi với dịch vụ ký; quyền ký một văn bản vẫn thuộc người được giao thẩm quyền và phải được kiểm tra riêng.',
 'Kết nối và chữ ký thử đạt','Kết nối hoặc chữ ký lỗi','Quản trị\nkết nối|Cấu hình\ndịch vụ ký|Kiểm tra\nkết nối ký|Cấu hình\nvà kết quả thử',
 'Chọn cấu hình cần kiểm tra|Gửi yêu cầu thử kết nối|Đọc cấu hình đã được cấp|Thông tin cấu hình kết nối|Ghi kết quả ký tài liệu thử|Kết quả kiểm tra kết nối|Trả kết quả để xem xét|Hiển thị lỗi hoặc kết quả thử')
add(12,'Kiểm tra hồ sơ và ghi nhận việc tiếp nhận chính thức tại cơ quan có thẩm quyền.',
 'Hồ sơ đang chờ tiếp nhận và cán bộ được giao tiếp nhận tại cơ quan được chọn.',
 'Cán bộ mở hồ sơ chờ tiếp nhận.|Cán bộ kiểm tra người nộp, thẩm quyền và thành phần hồ sơ.|Nếu hồ sơ đủ điều kiện, cán bộ xác nhận tiếp nhận.|Hệ thống cấp mã hồ sơ chính thức, tính thời hạn theo thủ tục và lập giấy hẹn.',
 'Hồ sơ chuyển sang đã tiếp nhận; người nộp nhận được mã hồ sơ và giấy hẹn.',
 'Nếu còn thiếu thành phần có thể bổ sung, cán bộ lập yêu cầu bổ sung và nêu căn cứ. Nếu từ chối tiếp nhận, cán bộ phải ghi lý do và thực hiện theo thẩm quyền; không dùng yêu cầu bổ sung thay cho thông báo từ chối.',
 'Tiếp nhận là thời điểm cơ quan xác nhận hồ sơ đủ điều kiện để xử lý. Đây cũng là căn cứ xác định thời hạn theo quy định của từng thủ tục. Quy tắc nhận hồ sơ sau 15 giờ chỉ được cấu hình cho thủ tục có quy định tương ứng, không áp dụng chung cho mọi hồ sơ.',
 'Hồ sơ đủ điều kiện nhận','Hồ sơ cần bổ sung','Cán bộ\ntiếp nhận|Tiếp nhận\nhồ sơ|Xử lý\ntiếp nhận|Hồ sơ\nvà giấy hẹn',
 'Kiểm tra và chọn tiếp nhận|Gửi xác nhận tiếp nhận|Đối chiếu thành phần và thẩm quyền|Kết quả kiểm tra tiếp nhận|Lưu tiếp nhận và giấy hẹn|Mã hồ sơ và thời hạn|Trả giấy hẹn đã lập|Hiển thị xác nhận tiếp nhận')
add(13,'Gửi yêu cầu bổ sung rõ ràng và ghi nhận tài liệu người nộp gửi lại.',
 'Hồ sơ đang được kiểm tra hoặc thẩm định. Cán bộ có trách nhiệm xử lý ở giai đoạn phát hiện thiếu thông tin.',
 'Cán bộ chỉ rõ nội dung còn thiếu và căn cứ yêu cầu bổ sung.|Hệ thống lưu giai đoạn đang xử lý và gửi thông báo cho người nộp.|Người nộp gửi tài liệu theo yêu cầu.|Cán bộ kiểm tra tài liệu bổ sung.|Nếu đạt yêu cầu, hệ thống đưa hồ sơ trở lại giai đoạn xử lý đã lưu; nếu chưa đạt, cán bộ nêu nội dung cần làm rõ.',
 'Tài liệu bổ sung được gắn với đúng yêu cầu. Hồ sơ tiếp tục tại giai đoạn trước khi yêu cầu bổ sung.',
 'Hệ thống không tự đặt lại thời hạn khi nhận tài liệu bổ sung. Tài liệu chưa đáp ứng yêu cầu phải được phản hồi rõ nội dung cần sửa; hết thời gian chờ không tự động được coi là từ chối hồ sơ.',
 'Hồ sơ có thể cần bổ sung ngay khi tiếp nhận hoặc trong quá trình thẩm định. Hệ thống phải ghi nhớ giai đoạn phát sinh yêu cầu để sau khi bổ sung không đưa hồ sơ về đầu quy trình. Người nộp cần xem được từng nội dung còn thiếu và biết tài liệu mình gửi đã được cán bộ kiểm tra hay chưa.',
 'Tài liệu bổ sung đạt yêu cầu','Tài liệu chưa đạt yêu cầu','Cán bộ\nxử lý|Bổ sung\nhồ sơ|Xử lý\nbổ sung|Yêu cầu\nvà tài liệu bổ sung',
 'Lập nội dung yêu cầu bổ sung|Gửi yêu cầu có căn cứ|Lưu yêu cầu và giai đoạn xử lý|Đã lưu yêu cầu bổ sung|Ghi nhận tài liệu đã kiểm tra|Đã ghi nhận đủ bổ sung|Trả giai đoạn tiếp tục xử lý|Hiển thị hồ sơ đã bổ sung')
add(14,'Giao hồ sơ cho chuyên viên có trách nhiệm xử lý.',
 'Hồ sơ đã được tiếp nhận và lãnh đạo có quyền phân công tại cơ quan đang giải quyết.',
 'Lãnh đạo chọn hồ sơ cần phân công.|Lãnh đạo chọn chuyên viên còn quyền xử lý và ghi yêu cầu công việc.|Hệ thống kiểm tra phạm vi của chuyên viên và tình trạng hồ sơ.|Lãnh đạo xác nhận; hệ thống đưa hồ sơ vào danh sách công việc của chuyên viên.',
 'Hồ sơ có một phân công đang có hiệu lực; người được giao nhìn thấy công việc trong danh sách của mình.',
 'Nếu phân công lại, hệ thống kết thúc phân công cũ và ghi phân công mới trong một lần lưu. Lịch sử người đã được giao xử lý không bị xóa.',
 'Phân công giúp xác định ai chịu trách nhiệm ở từng thời điểm. Khi cần chuyển việc cho chuyên viên khác, lãnh đạo phải ghi nhận việc phân công lại trên hệ thống. Cách làm này tránh tình trạng hai người cùng được coi là người xử lý chính mà không xác định được trách nhiệm.',
 'Chuyên viên có quyền xử lý','Chuyên viên không phù hợp','Lãnh đạo\nđơn vị|Phân công\nhồ sơ|Xử lý\nphân công|Thông tin\nphân công',
 'Chọn hồ sơ và chuyên viên|Gửi yêu cầu phân công|Kiểm tra quyền và phân công cũ|Kết quả kiểm tra người nhận|Lưu phân công đang có hiệu lực|Đã giao hồ sơ cho chuyên viên|Trả danh sách công việc|Hiển thị người được giao')
add(15,'Thẩm định hồ sơ, lấy ý kiến phối hợp và lập dự thảo kết quả để trình duyệt.',
 'Chuyên viên được phân công và có quyền đọc dữ liệu cần thiết. Các cơ quan phải lấy ý kiến được xác định theo quy trình thủ tục.',
 'Chuyên viên đối chiếu hồ sơ với dữ liệu và quy định chuyên ngành.|Khi cần phối hợp, chuyên viên gửi yêu cầu đến đúng cơ quan và ghi thời hạn trả lời.|Chuyên viên kiểm tra các ý kiến nhận được.|Chuyên viên lập dự thảo kết quả và trình người có thẩm quyền khi đủ căn cứ.',
 'Ý kiến phối hợp và dự thảo được lưu; hồ sơ chuyển sang chờ duyệt khi đã đáp ứng điều kiện trình.',
 'Nếu dữ liệu chuyên ngành không truy cập được, hệ thống ghi nhận lỗi kết nối, không kết luận dữ liệu đó không tồn tại. Ý kiến còn thiếu hoặc cần sửa phải được xử lý trước khi tổng hợp.',
 'Thẩm định phải cho thấy chuyên viên đã kiểm tra những gì và căn cứ nào dẫn đến dự thảo kết quả. Nếu nhiều cơ quan cùng tham gia, mỗi yêu cầu phối hợp có người nhận và thời hạn riêng. Hồ sơ chỉ được trình duyệt khi đủ ý kiến bắt buộc hoặc có quyết định xử lý ngoại lệ theo thẩm quyền.',
 'Đủ căn cứ và ý kiến bắt buộc','Thiếu căn cứ hoặc ý kiến','Chuyên viên\nthụ lý|Thẩm định\nhồ sơ|Tổng hợp\nthẩm định|Ý kiến\nvà dự thảo',
 'Nhập căn cứ và ý kiến thẩm định|Gửi dự thảo để kiểm tra|Đối chiếu các ý kiến bắt buộc|Danh sách ý kiến đã nhận|Lưu dự thảo đủ điều kiện|Đã lưu dự thảo trình duyệt|Trả nội dung cần người duyệt xem|Hiển thị hồ sơ chờ duyệt')
add(16,'Phê duyệt dự thảo và phát hành kết quả theo đúng trách nhiệm của lãnh đạo và văn thư.',
 'Dự thảo đã được chuyên viên trình. Người duyệt có thẩm quyền; người ký và văn thư được giao thực hiện các bước tương ứng.',
 'Lãnh đạo đọc dự thảo và căn cứ thẩm định.|Lãnh đạo phê duyệt hoặc trả chuyên viên chỉnh sửa.|Người có thẩm quyền ký bản đã được duyệt.|Văn thư kiểm tra chữ ký, cấp số và phát hành.|Hệ thống lưu bản kết quả đã phát hành và tạo thông báo trả kết quả.',
 'Kết quả có bản đã ký, số văn bản và thông tin phát hành. Hồ sơ chưa được coi là đã giao cho người nộp ở bước này.',
 'Nếu lãnh đạo yêu cầu chỉnh sửa, dự thảo trở lại chuyên viên. Nếu chữ ký lỗi, hệ thống giữ bản đã duyệt và chưa cho phát hành. Nội dung tệp đã ký không được sửa trực tiếp.',
 'Phê duyệt, ký và phát hành là ba việc khác nhau. Lãnh đạo quyết định nội dung, người có thẩm quyền ký chịu trách nhiệm về bản ký, còn văn thư kiểm tra và phát hành văn bản. Sau phát hành, cán bộ trả kết quả tiếp tục thực hiện UC18 để giao kết quả và ghi nhận người nhận.',
 'Bản đã ký đủ điều kiện phát hành','Chưa đủ điều kiện phát hành','Văn thư|Phát hành\nkết quả|Xử lý\nphát hành|Kết quả\nđã được ký',
 'Chọn bản đã ký để phát hành|Gửi yêu cầu cấp số và phát hành|Kiểm tra phê duyệt và chữ ký|Kết quả kiểm tra bản ký|Lưu số và bản phát hành|Đã phát hành kết quả|Trả số văn bản và bản phát hành|Hiển thị kết quả đã phát hành')
add(17,'Ghi nhận quyết định dừng giải quyết hồ sơ theo căn cứ và thẩm quyền.',
 'Hồ sơ chưa kết thúc. Đề nghị dừng và người có thẩm quyền quyết định đã được xác định.',
 'Cán bộ lập hoặc mở đề nghị dừng hồ sơ.|Người có thẩm quyền xem căn cứ và các công việc còn lại.|Người có thẩm quyền duyệt quyết định dừng.|Hệ thống cập nhật hồ sơ, gửi thông báo và chuyển xử lý khoản thu còn liên quan nếu có.',
 'Hồ sơ có quyết định dừng, lý do và thời điểm dừng. Công việc xử lý tài chính còn lại được theo dõi riêng.',
 'Người nộp đề nghị rút hồ sơ chưa đồng nghĩa hồ sơ đã được dừng. Hồ sơ đã kết thúc không được mở lại hoặc đổi trạng thái bằng lệnh dừng thông thường.',
 'Dừng giải quyết cần có quyết định rõ ràng để tránh nhầm với việc người dùng thoát màn hình hoặc không tiếp tục kê khai. Hệ thống giữ lịch sử đã xử lý và chỉ dừng các công việc phù hợp với quyết định. Nếu có khoản phải hoàn, cán bộ tài chính xử lý theo UC33.',
 'Có quyết định dừng hợp lệ','Chưa có quyết định dừng','Người có\nthẩm quyền|Dừng giải\nquyết hồ sơ|Xử lý\nquyết định dừng|Hồ sơ\nvà quyết định',
 'Chọn hồ sơ và quyết định dừng|Gửi xác nhận dừng giải quyết|Kiểm tra quyết định và trạng thái|Kết quả kiểm tra điều kiện dừng|Lưu lý do và thời điểm dừng|Đã dừng xử lý hồ sơ|Trả thông báo dừng giải quyết|Hiển thị quyết định đã ghi nhận')
add(18,'Giao bản kết quả đã phát hành và ghi nhận bằng chứng người có quyền đã nhận.',
 'Kết quả đã được phát hành. Cán bộ trả kết quả được giao xử lý và người nhận hoặc địa chỉ nhận đã được xác định.',
 'Cán bộ chọn kết quả chính thức cần trả.|Cán bộ kiểm tra người nhận hoặc quyền nhận qua kênh điện tử.|Cán bộ thực hiện giao trực tiếp, qua mạng hoặc bưu chính theo thủ tục.|Hệ thống lưu bằng chứng giao và cập nhật việc hoàn thành.',
 'Có thông tin người nhận, thời điểm và bằng chứng giao kết quả. Hồ sơ được ghi nhận hoàn thành khi đủ điều kiện.',
 'Nếu giao thất bại, hệ thống lưu lý do để tiếp tục xử lý. Việc gửi tin nhắn thông báo có kết quả chưa chứng minh người nộp đã nhận được kết quả.',
 'Trả kết quả cần phân biệt việc thông báo với việc giao thực tế. Với bản giấy, cán bộ ghi nhận người nhận và chứng từ giao. Với bản điện tử, hệ thống ghi nhận kết quả đã được đưa đến đúng tài khoản hoặc kho được phép nhận theo quy định của kênh trả.',
 'Có bằng chứng giao hợp lệ','Chưa xác nhận giao được','Cán bộ\ntrả kết quả|Giao\nkết quả|Xác nhận\ngiao nhận|Kết quả\nvà chứng từ giao',
 'Nhập người nhận và chứng từ|Gửi xác nhận đã giao|Kiểm tra bản phát hành và người nhận|Kết quả kiểm tra giao nhận|Lưu bằng chứng giao kết quả|Đã xác nhận người nhận|Trả tình trạng đã giao|Hiển thị hồ sơ hoàn thành')
add(19,'In hoặc tải tài liệu của hồ sơ bằng đúng biểu mẫu và phiên bản.',
 'Cán bộ có quyền xem hồ sơ và quyền in hoặc tải tài liệu được chọn.',
 'Cán bộ chọn giấy hẹn, phiếu hoặc kết quả cần in.|Hệ thống lấy dữ liệu và biểu mẫu đang áp dụng.|Cán bộ xem trước để kiểm tra bố cục và nội dung.|Cán bộ in hoặc tải tài liệu; hệ thống ghi lại việc kết xuất.',
 'Tài liệu được tạo bằng đúng mẫu; hệ thống có lịch sử in hoặc tải.',
 'Bản dự thảo phải được phân biệt với bản đã phát hành. Người không có quyền kết xuất không được tải tài liệu qua địa chỉ trực tiếp.',
 'Chức năng in cần bảo đảm nội dung trên giấy khớp với dữ liệu của hồ sơ, gồm mã hồ sơ, người nộp và thời hạn nếu biểu mẫu có các trường này. Xem trước giúp cán bộ phát hiện thiếu nội dung hoặc lỗi bố cục trước khi giao giấy cho người dân.',
 'Được phép in tài liệu','Không có quyền kết xuất','Cán bộ\nđược giao|In và tải\ntài liệu|Tạo\nbiểu mẫu|Dữ liệu\nvà mẫu tài liệu',
 'Chọn tài liệu cần in|Yêu cầu tạo bản xem trước|Lấy dữ liệu và mẫu áp dụng|Dữ liệu của bản tài liệu|Tạo bản in đúng phiên bản|Tài liệu sẵn sàng in|Trả bản xem trước|Hiển thị tài liệu cần in')
add(20,'Gửi thông báo về hồ sơ và nhắc cán bộ thực hiện công việc đến hạn.',
 'Người gửi hoặc tác vụ tự động được phép gửi thông báo. Người nhận và kênh liên lạc đã được xác định.',
 'Cán bộ chọn sự kiện cần thông báo hoặc thiết lập lịch nhắc.|Hệ thống lấy người nhận và nội dung được phép gửi.|Hệ thống chuyển thông báo qua kênh đã được xác nhận.|Cán bộ theo dõi thông báo đã gửi được hay cần gửi lại.',
 'Thông báo có người nhận, thời điểm gửi và kết quả gửi; lỗi gửi được theo dõi để xử lý tiếp.',
 'Tin nhắn không chứa nội dung hồ sơ cần bảo vệ. Khi gửi lại, hệ thống giữ mã thông báo để tránh tạo nhiều thông báo cho cùng một sự kiện.',
 'Người nộp cần được thông báo khi hồ sơ được tiếp nhận, yêu cầu bổ sung hoặc có kết quả. Cán bộ cần được nhắc khi công việc sắp đến hạn. Nội dung thông báo nên nêu việc cần làm và cách mở hồ sơ, thay vì gửi toàn bộ dữ liệu hồ sơ qua tin nhắn.',
 'Đúng người nhận và kênh gửi','Thiếu người nhận hoặc kênh','Cán bộ\nđược giao|Gửi\nthông báo|Xử lý\nthông báo|Thông báo\nvà kết quả gửi',
 'Chọn nội dung và người nhận|Gửi yêu cầu thông báo|Kiểm tra địa chỉ và nội dung|Kết quả kiểm tra người nhận|Lưu thông báo cần gửi|Mã thông báo và lịch gửi|Trả tình trạng gửi thông báo|Hiển thị thông báo đã lập')
add(21,'Tìm hồ sơ theo từ khóa và bộ lọc trong phạm vi người dùng được phép xem.',
 'Người dùng đã đăng nhập và được xác định quyền xem hồ sơ theo cơ quan hoặc quan hệ với hồ sơ.',
 'Người dùng nhập mã hồ sơ, tên hoặc từ khóa.|Người dùng chọn bộ lọc về thời gian, thủ tục và cơ quan trong phạm vi được giao.|Hệ thống lọc quyền trước khi tìm và tính số kết quả.|Người dùng mở hồ sơ hoặc tải danh sách khi có quyền tương ứng.',
 'Danh sách trả về chỉ gồm hồ sơ người dùng được phép xem. Việc tìm kiếm không sửa hồ sơ.',
 'Hệ thống không để số lượng kết quả hoặc gợi ý từ khóa làm lộ hồ sơ ngoài quyền truy cập. Không có kết quả phù hợp được thông báo rõ ràng.',
 'Tra cứu hồ sơ phải kiểm tra quyền ngay khi lấy dữ liệu. Nếu chỉ ẩn dòng trên màn hình sau khi đã tải dữ liệu, người dùng vẫn có thể đọc thông tin không thuộc quyền của mình. Vì vậy, cả danh sách, tổng số kết quả và tệp tải về phải dùng cùng phạm vi được phép xem.',
 'Bộ lọc trong phạm vi được giao','Yêu cầu vượt quyền truy cập','Người dùng\nđược cấp quyền|Tìm kiếm\nhồ sơ|Xử lý\ntìm kiếm|Danh sách\nhồ sơ được phép',
 'Nhập từ khóa và bộ lọc|Gửi yêu cầu tìm hồ sơ|Kiểm tra phạm vi người dùng|Phạm vi được phép tra cứu|Tìm hồ sơ theo bộ lọc|Danh sách hồ sơ phù hợp|Trả danh sách và số kết quả|Hiển thị hồ sơ được phép xem')
add(22,'Giúp cán bộ tìm hướng dẫn và văn bản còn hiệu lực để xử lý một thủ tục.',
 'Cán bộ có quyền tra cứu tài liệu; tài liệu có nguồn và ngày bắt đầu áp dụng được xác định.',
 'Cán bộ chọn thủ tục và ngày áp dụng cần tra cứu.|Cán bộ nhập nội dung cần tìm.|Hệ thống tìm tài liệu phù hợp và hiển thị nguồn, thời gian áp dụng.|Cán bộ đọc văn bản và đối chiếu trước khi quyết định xử lý hồ sơ.',
 'Cán bộ nhận được tài liệu phù hợp với thủ tục và thời điểm cần tra cứu.',
 'Tài liệu hết hiệu lực phải có cảnh báo và liên kết tới tài liệu thay thế khi đã xác định. Kết quả tra cứu không tự phê duyệt hoặc từ chối hồ sơ.',
 'Hướng dẫn hỗ trợ cán bộ hiểu cách xử lý, nhưng không thay cho việc đọc văn bản áp dụng. Khi quy định thay đổi, hệ thống cần giữ tài liệu cũ để giải thích cách xử lý hồ sơ ở thời điểm trước, đồng thời chỉ rõ tài liệu nào đang được sử dụng.',
 'Tài liệu phù hợp và còn hiệu lực','Không có tài liệu phù hợp','Cán bộ\nđược giao|Tra cứu\nhướng dẫn|Tìm\nvăn bản áp dụng|Tài liệu\nhướng dẫn',
 'Chọn thủ tục và ngày áp dụng|Gửi nội dung cần tra cứu|Kiểm tra hiệu lực tài liệu|Danh sách nguồn phù hợp|Lấy hướng dẫn theo thời điểm|Nội dung và nguồn văn bản|Trả hướng dẫn có nguồn|Hiển thị văn bản cần đọc')
add(23,'Tổng hợp báo cáo hồ sơ theo mẫu và kỳ báo cáo được chọn.',
 'Người lập báo cáo có quyền xem số liệu của cơ quan. Mẫu và kỳ báo cáo đã được xác định.',
 'Người dùng chọn mẫu báo cáo và kỳ số liệu.|Hệ thống xác định tập hồ sơ, thời điểm lấy số liệu và quy tắc tính.|Hệ thống tổng hợp; người dùng kiểm tra các tổng và hồ sơ tạo nên số liệu.|Người dùng kết xuất báo cáo có thời điểm lập và phạm vi cơ quan.',
 'Báo cáo có mẫu, kỳ, phạm vi và thời điểm lấy số liệu rõ ràng; hồ sơ nguồn không bị sửa.',
 'Hồ sơ liên thông xuất hiện ở nhiều hệ thống phải được nhận diện để không đếm trùng. Không cộng các số liệu khác kỳ hoặc khác cách tính.',
 'Một báo cáo cần giải thích được số liệu lấy từ những hồ sơ nào. Chẳng hạn, số hồ sơ đã giải quyết trong tháng phải dựa trên mốc hoàn thành của cùng kỳ và cùng phạm vi cơ quan. Người kiểm tra báo cáo cần mở được danh sách hồ sơ góp vào từng chỉ tiêu để đối chiếu khi phát hiện chênh lệch.',
 'Mẫu và kỳ báo cáo hợp lệ','Chưa xác định được tập số liệu','Người lập\nbáo cáo|Tổng hợp\nbáo cáo|Tính\nsố liệu báo cáo|Mẫu và\ndữ liệu báo cáo',
 'Chọn mẫu và kỳ báo cáo|Gửi yêu cầu tổng hợp|Kiểm tra phạm vi và kỳ số liệu|Quy tắc lấy số liệu|Tổng hợp hồ sơ theo mẫu|Các chỉ tiêu và hồ sơ nguồn|Trả báo cáo đã tổng hợp|Hiển thị số liệu cần kiểm tra')
add(24,'Quản lý biểu mẫu và công thức tính của các báo cáo.',
 'Người quản trị được giao thiết lập báo cáo; người phê duyệt mẫu đã được xác định.',
 'Người quản trị tạo bản nháp mẫu báo cáo.|Người quản trị khai báo cột, công thức, bộ lọc và thời gian áp dụng.|Hệ thống tính thử bằng dữ liệu đã biết để người quản trị đối chiếu.|Người có thẩm quyền duyệt mẫu; hệ thống công bố mẫu từ ngày áp dụng.',
 'Mẫu được công bố với công thức và thời gian áp dụng. Các báo cáo đã chốt giữ mẫu đã sử dụng.',
 'Nếu công thức tính thử cho kết quả sai, mẫu chưa được công bố. Sửa công thức phải tạo phiên bản mới, không làm thay đổi báo cáo đã lập trước đó.',
 'Mẫu báo cáo phải quy định rõ cách tính từng chỉ tiêu. Ví dụ, mẫu cần xác định hồ sơ đã rút có được đưa vào tổng số tiếp nhận hay không. Khi cách tính thay đổi, việc lưu phiên bản giúp người đọc hiểu vì sao hai báo cáo của các thời kỳ có số liệu khác nhau.',
 'Mẫu đã được kiểm tra và duyệt','Công thức còn lỗi','Quản trị\nnghiệp vụ|Quản lý\nmẫu báo cáo|Kiểm tra\ncông thức báo cáo|Phiên bản\nmẫu báo cáo',
 'Khai báo cột và công thức|Gửi mẫu để tính thử|Đối chiếu kết quả mẫu|Kết quả kiểm tra công thức|Lưu mẫu đã được duyệt|Đã công bố mẫu báo cáo|Trả mẫu và ngày áp dụng|Hiển thị mẫu đã công bố')
add(25,'Thống kê số lượng và tình trạng hồ sơ theo cơ quan, thủ tục và thời gian.',
 'Người dùng được xem số liệu trong phạm vi thống kê và biết cách tính chỉ tiêu được chọn.',
 'Người dùng chọn chỉ tiêu cần xem.|Người dùng chọn cơ quan, thủ tục và khoảng thời gian.|Hệ thống tính theo quy tắc của chỉ tiêu và ghi thời điểm cập nhật.|Người dùng xem biểu đồ, bảng số liệu và danh sách hồ sơ để đối chiếu.',
 'Số liệu có phạm vi, kỳ và thời điểm cập nhật rõ ràng; người dùng mở được hồ sơ tạo nên kết quả.',
 'Nếu dữ liệu chưa đồng bộ đủ, hệ thống cảnh báo số liệu có thể chậm cập nhật. Lỗi đồng bộ không được dùng để kết luận hồ sơ chưa hoàn thành.',
 'Thống kê hỗ trợ theo dõi tình hình xử lý nhưng cần có cách tính thống nhất. Tỷ lệ đúng hạn phải nêu rõ tập hồ sơ dùng làm mẫu số và các trường hợp được loại trừ. Hệ thống cũng cần tách số hồ sơ phải bổ sung khỏi tổng số lần bổ sung để người đọc không nhầm hai chỉ tiêu.',
 'Phạm vi và chỉ tiêu hợp lệ','Chưa xác định cách tính','Người xem\nthống kê|Thống kê\nhồ sơ|Tính\nchỉ tiêu hồ sơ|Hồ sơ\nvà số liệu',
 'Chọn chỉ tiêu và thời gian|Gửi yêu cầu thống kê|Kiểm tra cách tính chỉ tiêu|Quy tắc và phạm vi tính|Thống kê hồ sơ phù hợp|Số liệu và thời điểm cập nhật|Trả bảng thống kê|Hiển thị số liệu và cảnh báo')
add(26,'Giúp lãnh đạo theo dõi hồ sơ sắp đến hạn, quá hạn và người đang chịu trách nhiệm.',
 'Lãnh đạo có quyền xem tình hình xử lý của đơn vị được giao quản lý.',
 'Lãnh đạo chọn cơ quan và thời điểm cần theo dõi.|Hệ thống lọc hồ sơ sắp đến hạn hoặc quá hạn theo quy tắc của từng thủ tục.|Lãnh đạo xem người được giao và lý do chậm xử lý.|Lãnh đạo mở chức năng chỉ đạo khi cần giao việc hoặc yêu cầu giải trình.',
 'Lãnh đạo xem được danh sách cần theo dõi. Việc tra cứu không tự chuyển bước hoặc thay đổi thời hạn hồ sơ.',
 'Cảnh báo quá hạn chỉ phản ánh kết quả tính thời gian. Cảnh báo không tự dừng thời hạn, không tự kết luận trách nhiệm và không thay quyết định xử lý.',
 'Màn hình điều hành nên giúp lãnh đạo tìm công việc cần can thiệp, thay vì chỉ hiển thị tổng số hồ sơ. Từng dòng cần cho biết thủ tục, hạn xử lý, người đang được giao và bước hiện tại. Chỉ đạo phát sinh từ việc theo dõi này được ghi riêng tại UC27.',
 'Đúng đơn vị được quản lý','Ngoài phạm vi quản lý','Lãnh đạo\nđơn vị|Theo dõi\nxử lý hồ sơ|Tìm\ncông việc đến hạn|Hồ sơ\nvà phân công',
 'Chọn đơn vị và mốc theo dõi|Gửi yêu cầu xem công việc|Kiểm tra phạm vi quản lý|Cơ quan được phép theo dõi|Lọc hồ sơ và người xử lý|Danh sách hồ sơ đến hạn|Trả danh sách cần theo dõi|Hiển thị trách nhiệm xử lý')
add(27,'Ghi và gửi chỉ đạo xử lý để theo dõi trách nhiệm thực hiện.',
 'Người chỉ đạo có quyền tại cơ quan; cán bộ nhận chỉ đạo và hồ sơ liên quan đã được xác định.',
 'Lãnh đạo nhập nội dung chỉ đạo.|Lãnh đạo chọn người nhận, hồ sơ liên quan và hạn báo cáo.|Hệ thống gửi chỉ đạo và ghi nhận việc tiếp nhận.|Lãnh đạo theo dõi phản hồi, yêu cầu làm rõ hoặc xác nhận đã hoàn thành.',
 'Chỉ đạo có người giao, người nhận, thời hạn và lịch sử phản hồi để theo dõi thực hiện.',
 'Chỉ đạo không cho phép cán bộ bỏ qua điều kiện của thủ tục hoặc thay người có thẩm quyền ký quyết định.',
 'Chỉ đạo cần nêu việc phải làm, người chịu trách nhiệm và thời hạn trả lời. Chẳng hạn, lãnh đạo có thể yêu cầu chuyên viên làm rõ nguyên nhân hồ sơ chậm xử lý. Việc thực hiện chỉ đạo được theo dõi riêng, còn quyết định giải quyết hồ sơ vẫn tuân theo quy trình của thủ tục.',
 'Người nhận được xác định','Thiếu người nhận chỉ đạo','Lãnh đạo\nđơn vị|Ban hành\nchỉ đạo|Xử lý\nchỉ đạo|Chỉ đạo\nvà phản hồi',
 'Nhập chỉ đạo và hạn báo cáo|Gửi chỉ đạo cho người nhận|Kiểm tra quyền và nơi nhận|Kết quả kiểm tra chỉ đạo|Lưu chỉ đạo và trách nhiệm|Mã chỉ đạo đã ban hành|Trả tình trạng tiếp nhận|Hiển thị chỉ đạo cần theo dõi')
add(28,'Quản lý tài liệu trong kho và quyết định ai được khai thác tài liệu.',
 'Người quản trị kho được giao trách nhiệm; chủ sở hữu, nguồn tài liệu và thời hạn bảo quản đã được xác định.',
 'Người quản trị kiểm tra nguồn và chủ sở hữu tài liệu.|Người quản trị phân loại, ghi thời gian áp dụng và thời hạn bảo quản.|Người có quyền cho phép hoặc thu hồi quyền khai thác.|Hệ thống ghi lịch sử quyền và giữ thông tin các phiên bản tài liệu.',
 'Tài liệu có thông tin nguồn, chủ sở hữu và quyền sử dụng rõ ràng; các thay đổi quyền có lịch sử.',
 'Quản trị máy chủ không tự có quyền đọc toàn bộ kho tài liệu của công dân. Khi quyền bị thu hồi, tài liệu không được tiếp tục cung cấp cho người dùng đó.',
 'Kho tài liệu cần quản lý cả nội dung và quyền sử dụng. Người dùng có thể được phép đọc một tài liệu nhưng chưa được phép dùng tài liệu đó để nộp thay cho người khác. Thiết kế phải kiểm tra quyền theo từng tài liệu và giữ lại nguồn để cán bộ đối chiếu khi cần.',
 'Có căn cứ cấp quyền kho','Không có căn cứ cấp quyền','Quản trị\nkho được giao|Quản lý\nkho tài liệu|Xử lý\nquyền tài liệu|Tài liệu\nvà quyền dùng',
 'Chọn tài liệu và quyền sử dụng|Gửi yêu cầu thay đổi quyền|Kiểm tra chủ sở hữu và căn cứ|Kết quả kiểm tra quyền kho|Lưu quyền được cho phép|Đã cập nhật quyền tài liệu|Trả danh sách quyền hiện tại|Hiển thị quyền khai thác')
add(29,'Dùng lại tài liệu đã có trong kho để bổ sung thành phần cho một hồ sơ mới.',
 'Người nộp có quyền sử dụng tài liệu; tài liệu còn phù hợp với yêu cầu của thủ tục và hồ sơ đang kê khai.',
 'Người nộp mở hồ sơ đang kê khai.|Người nộp chọn tài liệu được phép dùng trong kho.|Hệ thống kiểm tra người sở hữu, hiệu lực và yêu cầu thành phần hồ sơ.|Hệ thống gắn tài liệu vào hồ sơ và giữ thông tin nguồn.',
 'Hồ sơ có thành phần lấy từ kho; tài liệu gốc và thông tin nguồn không bị sửa.',
 'Tài liệu đã hết hiệu lực, bị thay thế hoặc bị thu hồi quyền phải được báo để người nộp chọn tài liệu khác. Cán bộ vẫn kiểm tra sự phù hợp khi tiếp nhận hồ sơ.',
 'Tái sử dụng giúp người dân không phải nộp lại tài liệu mà hệ thống đã có và được phép khai thác. Tuy nhiên, việc tài liệu nằm trong kho chưa chứng minh tài liệu đó đáp ứng mọi thủ tục. Hệ thống cần kiểm tra loại giấy tờ, người sở hữu và thời gian áp dụng trước khi gắn vào hồ sơ mới.',
 'Tài liệu được phép dùng lại','Tài liệu không phù hợp','Người nộp\nhồ sơ|Chọn tài liệu\ntừ kho|Kiểm tra\ntài liệu dùng lại|Tài liệu\nvà thành phần hồ sơ',
 'Chọn tài liệu trong kho|Yêu cầu dùng tài liệu cho hồ sơ|Kiểm tra quyền và hiệu lực|Kết quả kiểm tra tài liệu|Gắn tài liệu kèm nguồn|Đã thêm thành phần hồ sơ|Trả danh sách tài liệu đã chọn|Hiển thị tài liệu được dùng lại')
add(30,'Tiếp nhận thông tin xử lý do hệ thống kết nối gửi đến và cập nhật đúng hồ sơ.',
 'Hệ thống gửi đã được cho phép kết nối; định dạng thông tin, cách xác thực và quy tắc thứ tự đã được thống nhất.',
 'Hệ thống đối tác gửi thông tin cùng mã hồ sơ và mã sự kiện.|Hệ thống tiếp nhận kiểm tra danh tính nguồn và tính toàn vẹn dữ liệu.|Hệ thống kiểm tra mã đã nhận và thứ tự cập nhật.|Thông tin hợp lệ được áp dụng vào hồ sơ; thông tin cần đối chiếu được giữ riêng để xử lý.',
 'Thông tin hợp lệ được ghi một lần, gắn đúng hồ sơ và có kết quả phản hồi cho bên gửi.',
 'Cùng mã sự kiện nhưng nội dung khác phải được giữ riêng để kiểm tra. Thông tin gửi đến muộn không được làm hồ sơ quay về một trạng thái cũ.',
 'Trong kết nối giữa các hệ thống, một thông báo có thể được gửi lại nhiều lần khi bên gửi chưa nhận được phản hồi. Hệ thống cần nhận diện mã thông báo để cập nhật một lần. Bên vận hành cũng phải tra cứu được thông tin đã nhận, đã áp dụng hay đang chờ đối chiếu.',
 'Nguồn và sự kiện hợp lệ','Nguồn hoặc nội dung sai','Hệ thống\nđối tác|Cổng nhận\nthông tin|Xử lý\nthông tin nhận|Sự kiện\nvà hồ sơ liên quan',
 'Gửi sự kiện và mã hồ sơ|Chuyển thông tin cần xử lý|Kiểm tra nguồn, mã và thứ tự|Kết quả kiểm tra sự kiện|Áp dụng sự kiện chưa xử lý|Đã ghi sự kiện một lần|Trả kết quả tiếp nhận|Phản hồi cho hệ thống gửi')
add(31,'Gửi thông tin hồ sơ đến Cổng Dịch vụ công quốc gia hoặc hệ thống được phân tuyến.',
 'Thông tin cần gửi đã được lưu sau một bước xử lý hợp lệ; kết nối và cơ quan nhận đã được xác định.',
 'Tác vụ gửi lấy thông tin đang chờ trao đổi.|Hệ thống gửi thông tin kèm mã dùng để đối chiếu phản hồi.|Hệ thống đọc phản hồi và kiểm tra đúng hồ sơ, đúng lần gửi.|Hệ thống ghi nhận kết quả; nếu lỗi, lập lịch gửi lại theo quy tắc đã thống nhất.',
 'Mỗi thông tin có tình trạng gửi và phản hồi rõ ràng để cán bộ vận hành theo dõi.',
 'Chưa nhận được phản hồi không được coi là bên nhận đã áp dụng thông tin. Khi gửi lại, hệ thống giữ mã đối chiếu và không tạo thêm hồ sơ mới.',
 'Thông tin hồ sơ được gửi ra ngoài sau khi đã lưu thành công tại hệ thống xử lý. Cách thực hiện này giúp tránh việc bên nhận thấy một bước xử lý mà hệ thống nguồn chưa lưu được. Gửi thành công và bên nhận đã cập nhật là hai mốc cần được theo dõi riêng.',
 'Phản hồi đúng hồ sơ và lần gửi','Lỗi hoặc chưa có phản hồi','Tác vụ\ngửi thông tin|Theo dõi\nkết nối|Xử lý\ntrao đổi dữ liệu|Thông tin\nđang chờ gửi',
 'Lấy thông tin đến lượt gửi|Yêu cầu gửi đúng mã đối chiếu|Đọc thông tin đã lưu thành công|Nội dung và mã lần gửi|Ghi phản hồi từ bên nhận|Tình trạng gửi và phản hồi|Trả kết quả để theo dõi|Hiển thị lần gửi cần xử lý')
add(32,'Cho phép người nộp thanh toán khoản phí hoặc lệ phí của hồ sơ khi thủ tục có thu.',
 'Hồ sơ có thông báo thu hợp lệ; số tiền và trường hợp miễn, giảm đã được xác định theo quy định áp dụng.',
 'Người nộp xem khoản phải thanh toán.|Người nộp chọn phương thức thanh toán được hỗ trợ.|Người nộp xác nhận thanh toán tại đơn vị cung cấp dịch vụ.|Hệ thống kiểm tra phản hồi và cập nhật giao dịch; người nộp theo dõi chứng từ.',
 'Giao dịch có mã, số tiền và kết quả xác nhận; khoản thu chỉ được ghi đã thanh toán khi có phản hồi hợp lệ.',
 'Thủ tục không thu phí bỏ qua bước thanh toán. Nếu chưa có phản hồi, giao dịch giữ trạng thái chờ xác nhận; ảnh chụp thanh toán không được dùng thay cho dữ liệu đối soát.',
 'Người nộp cần biết phải trả khoản nào, số tiền bao nhiêu và căn cứ miễn, giảm nếu có. Sau khi chuyển sang bên thanh toán, hệ thống phải theo dõi phản hồi để tránh yêu cầu người dùng thanh toán lại chỉ vì màn hình chưa cập nhật. Cán bộ tài chính đối chiếu giao dịch qua UC33.',
 'Phản hồi thanh toán hợp lệ','Chưa xác nhận thanh toán','Người nộp\nhồ sơ|Thanh toán\ntrực tuyến|Xử lý\nthanh toán|Khoản thu\nvà giao dịch',
 'Chọn khoản và phương thức trả|Gửi yêu cầu thanh toán|Kiểm tra số tiền và người trả|Thông tin khoản thu hợp lệ|Lưu giao dịch đã xác nhận|Mã giao dịch và chứng từ|Trả kết quả thanh toán|Hiển thị khoản đã thanh toán')
add(33,'Đối chiếu giao dịch với khoản thu và xử lý đề nghị hoàn theo thẩm quyền.',
 'Cán bộ tài chính có quyền đối chiếu. Dữ liệu do đơn vị thanh toán cung cấp đã được xác thực.',
 'Cán bộ lấy dữ liệu giao dịch của kỳ cần đối chiếu.|Hệ thống ghép mã giao dịch với khoản thu và hồ sơ.|Cán bộ kiểm tra chênh lệch về số tiền hoặc trạng thái.|Cán bộ chốt kết quả đối chiếu hoặc lập đề nghị hoàn để người có thẩm quyền duyệt.',
 'Giao dịch đã được đối chiếu hoặc có nội dung chênh lệch cần xử lý; đề nghị hoàn có lịch sử phê duyệt.',
 'Phản hồi gửi lặp không được cộng thêm tiền. Giao dịch hoàn phải được duyệt riêng và gắn với khoản thu gốc.',
 'Đối soát kiểm tra việc ghi nhận thu có khớp với dữ liệu của đơn vị thanh toán hay không. Nếu tiền đã trả nhưng hồ sơ chưa ghi nhận, cán bộ dùng mã giao dịch để làm rõ. Nếu phát sinh hoàn, hệ thống cần theo dõi số tiền hoàn và người duyệt, tránh tính cả khoản đã hoàn vào tiền thu thực tế.',
 'Giao dịch khớp khoản thu','Có chênh lệch cần xử lý','Cán bộ\ntài chính|Đối chiếu\nthu và hoàn|Xử lý\nđối soát|Giao dịch\nvà khoản thu',
 'Chọn kỳ và dữ liệu đối chiếu|Gửi yêu cầu đối soát|Ghép mã giao dịch và số tiền|Danh sách chênh lệch|Lưu kết quả đối chiếu đã xác nhận|Đã chốt giao dịch phù hợp|Trả giao dịch cần xử lý tiếp|Hiển thị kết quả đối soát')
add(34,'Chuyển tài liệu giấy đã tiếp nhận thành tệp điện tử để xử lý và lưu hồ sơ.',
 'Cán bộ được phép số hóa; tài liệu giấy và hồ sơ cần gắn tệp đã được xác định.',
 'Cán bộ chọn thành phần hồ sơ cần số hóa.|Cán bộ quét đủ trang, kiểm tra chiều trang và độ rõ của ảnh.|Cán bộ đối chiếu tệp với tài liệu giấy được xuất trình.|Người có thẩm quyền xác nhận; hệ thống lưu tệp, số trang và nguồn tài liệu.',
 'Hồ sơ có tệp điện tử đọc được, đủ trang và có thông tin xác nhận việc đối chiếu.',
 'Tệp mờ, thiếu trang hoặc gắn nhầm hồ sơ phải được làm lại. Cán bộ không được xác nhận thay cho người có thẩm quyền.',
 'Số hóa không chỉ là quét giấy thành ảnh. Cán bộ còn phải kiểm tra đủ trang, đúng tài liệu và đúng hồ sơ. Thông tin nguồn và người đối chiếu giúp xác định bản điện tử được tạo từ tài liệu nào, phục vụ kiểm tra hoặc dùng lại về sau.',
 'Tệp rõ và đủ trang','Tệp mờ hoặc thiếu trang','Cán bộ\ntiếp nhận|Số hóa\ntài liệu giấy|Kiểm tra\ntệp hồ sơ|Thành phần\nhồ sơ điện tử',
 'Tải tệp quét và thông tin nguồn|Gửi tệp để kiểm tra|Kiểm tra trang và hồ sơ được gắn|Kết quả kiểm tra tệp quét|Lưu tệp đã được đối chiếu|Đã lưu thành phần số hóa|Trả tệp và người xác nhận|Hiển thị tài liệu điện tử')
add(35,'Tiếp nhận phản ánh hoặc đánh giá của người dân và theo dõi việc trả lời.',
 'Người gửi sử dụng đúng kênh phản ánh hoặc đánh giá; thông tin liên hệ đáp ứng yêu cầu của kênh tiếp nhận.',
 'Người gửi chọn loại phản ánh hoặc đánh giá.|Người gửi nhập nội dung, thông tin liên hệ và hồ sơ liên quan nếu có.|Hệ thống ghi nhận nội dung và cấp mã theo dõi.|Đơn vị được giao trả lời; người gửi xem kết quả hoặc yêu cầu làm rõ.',
 'Phản ánh có mã, nơi xử lý và lịch sử trả lời. Đánh giá được ghi đúng hồ sơ hoặc dịch vụ liên quan.',
 'Phản ánh không tự thay đổi quyết định giải quyết hồ sơ. Nội dung khiếu nại phải được hướng dẫn theo quy trình tiếp nhận có thẩm quyền riêng.',
 'Người dân cần theo dõi được phản ánh đã gửi, đơn vị đang xử lý và nội dung trả lời. Hệ thống phải phân biệt đánh giá chất lượng phục vụ với phản ánh cần giải quyết. Cả hai đều không thay cho việc nộp hồ sơ mới hoặc thực hiện thủ tục khiếu nại theo quy định.',
 'Nội dung và kênh phù hợp','Nội dung cần bổ sung','Người gửi\nphản ánh|Phản ánh\nvà đánh giá|Xử lý\nphản ánh|Phản ánh\nvà trả lời',
 'Nhập nội dung và liên hệ|Gửi phản ánh cần tiếp nhận|Kiểm tra kênh và nội dung trùng|Kết quả kiểm tra phản ánh|Lưu phản ánh và nơi xử lý|Mã theo dõi phản ánh|Trả xác nhận đã gửi|Hiển thị mã và nơi xử lý')
add(36,'Lập và chuyển hồ sơ đã hoàn thành vào lưu trữ của cơ quan.',
 'Hồ sơ đã kết thúc; thành phần phải lưu, thời hạn bảo quản và đơn vị nhận lưu đã được xác định.',
 'Cán bộ lưu trữ chốt danh sách hồ sơ và phiên bản tài liệu.|Cán bộ lập danh mục tệp trong gói nộp lưu.|Hệ thống kiểm tra đủ thành phần và tính toàn vẹn của các tệp.|Cán bộ gửi gói nộp lưu; hệ thống lưu biên nhận hoặc lý do bị trả lại.',
 'Hồ sơ có danh mục nộp lưu và biên nhận của nơi nhận. Nếu bị trả lại, hệ thống giữ lý do và theo dõi việc bổ sung.',
 'Gói thiếu tệp hoặc có tệp thay đổi phải được hoàn thiện trước khi gửi lại. Kho tài liệu của công dân không thay thế kho lưu trữ hồ sơ của cơ quan.',
 'Nộp lưu kết thúc việc lập hồ sơ xử lý và chuyển sang trách nhiệm bảo quản. Danh mục phải cho biết mỗi tệp thuộc hồ sơ nào, phiên bản nào và có thời hạn giữ bao lâu. Biên nhận giúp cơ quan chứng minh đã bàn giao đủ tài liệu, thay vì chỉ biết đã gửi một thư mục tệp.',
 'Gói nộp lưu đủ và toàn vẹn','Gói thiếu hoặc tệp thay đổi','Cán bộ\nlưu trữ|Nộp lưu\nhồ sơ|Kiểm tra\ngói nộp lưu|Hồ sơ\nvà biên nhận lưu',
 'Chọn hồ sơ và danh mục tệp|Gửi gói để kiểm tra|Đối chiếu thành phần và tệp|Kết quả kiểm tra gói lưu|Lưu biên nhận đúng phiên bản|Đã ghi nhận bàn giao lưu trữ|Trả tình trạng nộp lưu|Hiển thị hồ sơ đã bàn giao')

assert len(DATA)==36
if __name__=='__main__':
 (ROOT/'03_Thiet_ke/Huong_doi_tuong/Noi_dung_Use_case_20261003.json').write_text(json.dumps(list(DATA.values()),ensure_ascii=False,indent=2),encoding='utf-8')
 print('Đã biên tập nội dung cho 36 Use case.')
