from pathlib import Path
import json
import pypdfium2 as pdfium
from tao_thiet_ke import ROOT, OUT, FIG, diagram

source = ROOT/'01_Nguon_tham_khao/Bo_sung_2026/huong_dan_2023.pdf'
page = pdfium.PdfDocument(str(source))[26].render(scale=3).to_pil()
w,h=page.size
page.crop((int(w*.142),int(h*.275),int(w*.91),int(h*.538))).save(FIG/'17_giao_dien_thuc_te_2023.png')

diagram('18_phan_chia_he_thong',[(700,120,600,160,'Cổng Dịch vụ công quốc gia\nKênh giao dịch của công dân'),(80,430,620,190,'Hệ thống Thành phố\nThủ tục còn xử lý tại địa phương\nTheo tuyến đã được phê duyệt'),(1300,430,620,190,'Hệ thống tập trung của bộ\nTác nghiệp theo ngành\nQuyền và quy trình của bộ'),(80,810,620,160,'Cơ sở dữ liệu chuyên ngành\nTra cứu theo mục đích, thẩm quyền'),(1300,810,620,160,'Đối chiếu số liệu tại Thành phố\nMã nguồn, kỳ và mốc dữ liệu')],[(0,1,'Tuyến địa phương'),(0,2,'Tuyến bộ'),(1,3,'Khai thác có quyền'),(2,4,'Trạng thái, kết quả')],'Ranh giới được phân tích trong bối cảnh năm 2026')
diagram('19_phoi_hop',[(40,430,420,170,'Hồ sơ và cơ quan đầu mối\nGiữ hạn pháp lý'),(670,150,440,190,'Nhiệm vụ cơ quan A\nPhạm vi, hạn trả lời\nÝ kiến có phiên bản'),(670,700,440,190,'Nhiệm vụ cơ quan B\nBắt buộc hoặc có điều kiện\nÝ kiến có phiên bản'),(1440,430,500,190,'Tổng hợp và trình duyệt\nĐủ ý kiến bắt buộc\nHoặc có căn cứ xử lý khác')],[(0,1,'Giao nhiệm vụ A'),(0,2,'Giao nhiệm vụ B'),(1,3,'Ý kiến A'),(2,3,'Ý kiến B')],'Phối hợp nhiều cơ quan trong thiết kế đề xuất')
diagram('20_nop_luu',[(50,170,500,190,'Hồ sơ kết thúc\nChốt phiên bản và thành phần'),(750,170,500,190,'Lập gói nộp lưu\nTài liệu, ý kiến, dữ liệu đặc tả'),(1450,170,500,190,'Kiểm tra tại nơi nộp\nĐủ thành phần và toàn vẹn'),(1450,730,500,190,'Kho lưu trữ kiểm tra\nNhận hoặc yêu cầu bổ sung'),(750,730,500,190,'Ghi biên nhận\nGói, phiên bản, mốc nhận'),(50,730,500,190,'Khai thác theo quyền\nBảo quản và kiểm tra định kỳ')],[(0,1,'Tạo danh mục'),(1,2,'Chuẩn bị'),(2,3,'Gửi gói'),(3,4,'Xác nhận'),(4,5,'Theo dõi')],'Vòng đời nộp lưu hồ sơ điện tử được đề xuất')
diagram('21_quan_he_lien_thong',[(70,160,540,170,'ho_so\nPK id'),(730,160,540,170,'he_thong_ket_noi\nPK id'),(1390,160,540,170,'dot_nop_luu\nPK id'),(70,760,540,210,'tham_chieu_lien_thong\nFK ho_so, he_thong\nMã hồ sơ ngoài và mốc nguồn'),(730,760,540,210,'thong_diep_nhan\nFK he_thong, ho_so nếu có\nMã sự kiện và băm nội dung'),(1390,760,540,210,'ho_so_nop_luu\nFK dot_nop_luu, ho_so\nGói và biên nhận')],[(0,3,'1 : nhiều'),(1,4,'1 : nhiều'),(2,5,'1 : nhiều')],'Một số quan hệ bổ sung cho liên thông và nộp lưu')

schemas={
}
diagram('22_nhanh_chuc_nang',[(640,120,720,160,'Hệ thống giải quyết thủ tục\nHà Nội trong quan hệ liên thông'),(40,430,600,160,'Giao dịch và xử lý hồ sơ'),(700,430,600,160,'Giá trị kết quả và trao đổi'),(1360,430,600,160,'Kiểm soát và điều hành'),(40,750,600,250,'2. Danh mục, mẫu và hồ sơ\n4. Tiếp nhận và giải quyết\n5. Tiện ích hỗ trợ'),(700,750,600,250,'3. Chữ ký số\n8. Kho tổ chức, cá nhân\n9. Tích hợp và liên thông'),(1360,750,600,250,'1. Tài khoản và quyền\n6. Thống kê và báo cáo\n7. Điều hành tác nghiệp')],[(0,1,''),(0,2,''),(0,3,''),(1,4,''),(2,5,''),(3,6,'')],'Khung phân tích chín nhóm chức năng theo quy định')
schemas={
 'Route':{'type':'object','required':['procedureVersionId','systemId','effectiveFrom','legalBasis'],'properties':{'procedureVersionId':{'type':'string','format':'uuid'},'systemId':{'type':'string','format':'uuid'},'effectiveFrom':{'type':'string','format':'date-time'},'effectiveTo':{'type':'string','format':'date-time','nullable':True},'legalBasis':{'type':'string','minLength':1}}},
 'ExternalEvent':{'type':'object','required':['sourceSystem','eventId','externalCaseId','occurredAt','sequence','eventType','payload'],'properties':{'sourceSystem':{'type':'string'},'eventId':{'type':'string','maxLength':150},'externalCaseId':{'type':'string','maxLength':150},'occurredAt':{'type':'string','format':'date-time'},'sequence':{'type':'integer','minimum':1},'eventType':{'type':'string','enum':['RECEIVED','ACCEPTED','ASSESSMENT','ISSUED','DELIVERED','STOPPED']},'payload':{'type':'object','description':'Dữ liệu theo hợp đồng được duyệt, không nhận trường tùy ý'}}},
 'Task':{'type':'object','required':['caseId','recipientAgencyId','scope','mandatory','dueAt','version'],'properties':{'caseId':{'type':'string','format':'uuid'},'recipientAgencyId':{'type':'string','format':'uuid'},'scope':{'type':'string','minLength':1},'mandatory':{'type':'boolean'},'dueAt':{'type':'string','format':'date-time'},'version':{'type':'integer','minimum':1}}},
 'ArchivePackage':{'type':'object','required':['packageId','caseId','manifestHash','items'],'properties':{'packageId':{'type':'string'},'caseId':{'type':'string','format':'uuid'},'manifestHash':{'type':'string','pattern':'^[0-9a-f]{64}$'},'items':{'type':'array','minItems':1,'items':{'type':'object','required':['documentId','version','sha256'],'properties':{'documentId':{'type':'string'},'version':{'type':'integer','minimum':1},'sha256':{'type':'string','pattern':'^[0-9a-f]{64}$'}}}}}},
 'Feedback':{'type':'object','required':['type','content'],'properties':{'type':{'type':'string','enum':['SERVICE_FEEDBACK','SATISFACTION','OTHER_PROCESS']},'content':{'type':'string','minLength':1,'maxLength':5000},'caseId':{'type':'string','format':'uuid','nullable':True}}},
 'Receipt':{'type':'object','required':['id','correlationId','status'],'properties':{'id':{'type':'string'},'correlationId':{'type':'string'},'status':{'type':'string','description':'Nhận thông điệp khác với áp dụng thành công nghiệp vụ'}}}
}
operations=[('get','/v1/routes','Tra cứu tuyến tác nghiệp',None),('post','/v1/external-events','Nhận sự kiện từ hệ thống được phép','ExternalEvent'),('post','/v1/coordination-tasks','Tạo nhiệm vụ phối hợp','Task'),('post','/v1/archive-packages','Gửi gói nộp lưu','ArchivePackage'),('post','/v1/feedback','Tiếp nhận phản ánh, đánh giá','Feedback'),('get','/v1/reports/reconciliation','Đối chiếu số liệu theo nguồn',None),('post','/v1/routes','Đề nghị cấu hình tuyến','Route')]
paths={}
schemas['RouteList']={'type':'object','required':['asOf','items'],'properties':{'asOf':{'type':'string','format':'date-time'},'items':{'type':'array','items':{'$ref':'#/components/schemas/Route'}}}}
schemas['Reconciliation']={'type':'object','required':['asOf','sourceSystem','caseCount','excludedDuplicates','pendingEvents'],'properties':{'asOf':{'type':'string','format':'date-time'},'sourceSystem':{'type':'string'},'caseCount':{'type':'integer','minimum':0},'excludedDuplicates':{'type':'integer','minimum':0},'pendingEvents':{'type':'integer','minimum':0},'lastSourceAt':{'type':'string','format':'date-time','nullable':True}}}
for i,(method,path,title,schema) in enumerate(operations):
 op={'operationId':f'extended{i+1}','summary':title,'security':[{'serviceAuth':[]} if path=='/v1/external-events' else {'bearerAuth':[]}], 'responses':{'200':{'description':'Kết quả tiếp nhận hoặc tra cứu','content':{'application/json':{'schema':{'$ref':'#/components/schemas/Receipt'}}}},'401':{'description':'Nguồn hoặc danh tính không hợp lệ'},'403':{'description':'Ngoài phạm vi quyền'},'409':{'description':'Xung đột phiên bản, tuyến hoặc thông điệp'},'422':{'description':'Không đủ điều kiện nghiệp vụ'}}}
 if schema:
  op['parameters']=[{'name':'Idempotency-Key','in':'header','required':True,'schema':{'type':'string','maxLength':150}}]
  op['requestBody']={'required':True,'content':{'application/json':{'schema':{'$ref':'#/components/schemas/'+schema}}}}
 else:
  op['responses']['200']['content']['application/json']['schema']={'$ref':'#/components/schemas/'+('RouteList' if path=='/v1/routes' else 'Reconciliation')}
  op['parameters']=[{'name':'asOf','in':'query','required':True,'schema':{'type':'string','format':'date-time'}}, {'name':'procedureVersionId' if path=='/v1/routes' else 'sourceSystem','in':'query','required':True,'schema':{'type':'string'}}]
 paths.setdefault(path,{})[method]=op
spec={'openapi':'3.0.3','info':{'title':'Giao tiếp mở rộng của thiết kế nghiên cứu','version':'2.0.0','description':'Không phải địa chỉ giao tiếp đang vận hành của Hà Nội. Cần thống nhất hợp đồng, nguồn trạng thái, xác thực thông điệp và chữ ký trước phát triển.'},'paths':paths,'components':{'schemas':schemas,'securitySchemes':{'bearerAuth':{'type':'http','scheme':'bearer'},'serviceAuth':{'type':'http','scheme':'bearer','description':'Danh tính dịch vụ đã cấp riêng; kiểm tra TLS hai chiều và chữ ký thông điệp theo hợp đồng ở tầng tích hợp'}}}}
(OUT/'Giao_tiep_mo_rong_OpenAPI.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2),encoding='utf-8')
print('Bổ sung bốn sơ đồ, một ảnh giao diện có nguồn và bảy giao tiếp.')
