from pathlib import Path
from copy import deepcopy
from zipfile import ZipFile,ZIP_DEFLATED
import json,re,csv,html
from PIL import Image
from docx.oxml.ns import qn
ROOT=Path(__file__).resolve().parents[1]
MODEL=json.loads((ROOT/'03_Thiet_ke/Huong_doi_tuong/Danh_muc_ca_su_dung.json').read_text('utf-8'))
BASE=ROOT/'03_Thiet_ke/Huong_doi_tuong'
MAPPING=json.loads((BASE/'Anh_xa_lop.json').read_text('utf-8'))
SCHEMA=json.loads((ROOT/'03_Thiet_ke/Tu_dien_du_lieu.json').read_text('utf-8'))
CONTRACT=json.loads((BASE/'Hop_dong_36_thao_tac.json').read_text('utf-8'))
ASSOC=json.loads((BASE/'Quan_he_lop_day_du.json').read_text('utf-8'))
MACHINE=json.loads((BASE/'May_trang_thai_ho_so.json').read_text('utf-8'))
CHECK=json.loads((BASE/'Ket_qua_kiem_tra_mo_hinh.json').read_text('utf-8'))
CAT=json.loads((ROOT/'07_Huong_dan/Thu_tuc_theo_QD_492/Danh_muc.json').read_text('utf-8'))
GROUPS={1:'Tài khoản và quyền',2:'Danh mục và quy trình',3:'Chữ ký số',4:'Tiếp nhận và giải quyết',5:'Tiện ích',6:'Thống kê và báo cáo',7:'Điều hành tác nghiệp',8:'Kho dữ liệu',9:'Tích hợp và liên thông'}
SOURCES=[
('[1]','Tài liệu công dân của Hệ thống thông tin giải quyết thủ tục hành chính thành phố Hà Nội, bản 1.0 năm 2023, Công ty TNHH Hệ thống thông tin FPT; tư liệu lịch sử','https://sqhx-hanoi.mediacdn.vn/documents/49866/0/_VB_1684301998055_VB_HDSD.pdf'),
('[2]','Trung tâm Phục vụ hành chính công: từ 01/07/2025, người dân thực hiện thủ tục trên Cổng Dịch vụ công quốc gia','https://ttpvhcc.hanoi.gov.vn/tien-ich-cong-dan/tu-ngay-01-07-2025-nguoi-dan-thuc-hien-thu-tuc-hanh-chinh-tren-dia-ban-thanh-pho-ha-noi-se-thuc-hien-tren-cong-dich-vu-cong-quoc-gia-2850250629165651829.htm'),
('[3]','Thông tư 21/2023/TT-BTTTT đọc cùng Thông tư 11/2025/TT-BKHCN; căn cứ xây dựng khung đối chiếu chức năng','https://vanban.chinhphu.vn/?classid=1&docid=214528&pageid=27160&typegroupid=6'),
('[4]','Quyết định 492/QĐ-TTPVHCC ngày 14/04/2026, ba phụ lục phân loại mức cung cấp trực tuyến','https://datafiles.hanoi.gov.vn/gov-hni/8123/VanBan/2026/4/22/QD%20492.pdf'),
('[5]','Quyết định 1811/QĐ-TTPVHCC ngày 24/12/2025, phương án tái cấu trúc thủ tục cấp bản sao trích lục hộ tịch','https://vanban.hanoi.gov.vn/chi-tiet-van-ban/ve-viec-phe-duyet-phuong-an-tai-cau-truc-thu-tuc-hanh-chinh-cap-ban-sao-trich-luc-ho-tich-ban-sao-g-230492'),
('[6]','Quyết định 663/QĐ-TTPVHCC ngày 13/05/2026, phụ lục trang 65 đến 69, cấp bản sao từ sổ gốc','https://datafiles.hanoi.gov.vn/gov-hni/6244/VanBan/2026/5/13/PLQDPVHCC-663-2026.pdf'),
('[7]','Cổng Dịch vụ công quốc gia, chi tiết công khai mã 2.000635, quan sát ngày 02/10/2026','https://dichvucong.gov.vn/thu-tuc-hanh-chinh/019d2bfd-867c-72db-b6a7-dcbd8c763807'),
('[8]','OMG, đặc tả UML 2.5.1, tháng 12/2017; căn cứ ký pháp, không phải căn cứ pháp lý của thủ tục','https://www.omg.org/spec/UML/2.5.1'),
('[9]','UBND Hà Nội, chỉ đạo tại Công văn 1747/UBND-NC ngày 25/04/2026 về phân tuyến hệ thống Thành phố và hệ thống tập trung của bộ','https://hanoi.gov.vn/chi-dao-cua-ubnd-thanh-pho-ha-noi/thuc-hien-tthc-dich-vu-cong-truc-tuyen-lien-thong-dong-bo-hieu-qua-4260429145849633.htm'),
('[10]','Nguồn chứng minh hệ thống Hà Nội vận hành từ 11/04/2023, công bố 03/07/2023','https://thanglong.chinhphu.vn/hoan-thanh-25-25-dich-vu-cong-thiet-yeu-theo-dung-lo-trinh-de-an-06-10323070313374254.htm')]

class Book:
 def __init__(self,name,title):
  env={'__file__':str(Path(__file__))};src=(ROOT/'06_Cong_cu/tao_bao_cao.py').read_text('utf-8').split("heading('LỜI CẢM ƠN')")[0];exec(src,env);self.e=env;self.d=env['d'];self.file=ROOT/'04_Bao_cao'/name
  for i,t in {10:title[0],11:title[1],35:title[0],36:title[1]}.items():
   p=self.d.element.body[i];r=p.find(qn('w:r'));rp=deepcopy(r.find(qn('w:rPr'))) if r is not None and r.find(qn('w:rPr')) is not None else None;env['replace_p'](p,t)
   if rp is not None:p.find(qn('w:r')).insert(0,rp)
 def h(self,t,lv=1):return self.e['heading'](t,lv)
 def p(self,t):return self.e['para'](t)
 def tab(self,ch,title,rows,widths=None):self.e['caption']('Bảng',str(ch),title);return self.e['table']([[str(x) for x in r] for r in rows],widths)
 def fig(self,ch,name,title,path=None):
  file=path or BASE/'So_do'/(name+'.png');im=Image.open(file);w,h=im.size;wt=min(9072,10400*w/h)
  p=self.d.add_paragraph();p.paragraph_format.alignment=self.e['WD_ALIGN_PARAGRAPH'].CENTER;p.paragraph_format.first_line_indent=self.e['Twips'](0);p.paragraph_format.keep_with_next=True;p.add_run().add_picture(str(file),width=self.e['Twips'](int(wt)));self.e['caption']('Hình',str(ch),title)
 def front(self,brief=False):
  self.h('LỜI CẢM ƠN');self.p('Em trân trọng cảm ơn giảng viên Hoàng Minh Ngọc đã hướng dẫn học phần Hệ thống thông tin quản lý hành chính. Tài liệu công khai của các cơ quan nhà nước và những kiến thức của học phần là căn cứ để em nghiên cứu đối tượng thực tế, phân tích trách nhiệm và xây dựng bản thiết kế.')
  self.h('LỜI CAM ĐOAN');self.p('Tài liệu được xây dựng từ nguồn công khai và hồ sơ nghiên cứu. Các mô hình lớp, giao tiếp, màn hình và hạ tầng là thiết kế đề xuất. Em chưa khảo sát tài khoản cán bộ, mã nguồn, dữ liệu nội bộ hoặc kiểm thử phần mềm đang vận hành của thành phố Hà Nội. Mọi kịch bản kiểm thử đều ghi trạng thái chưa thực hiện.')
  self.p('Giảng viên hướng dẫn: Hoàng Minh Ngọc. Sinh viên: Lê Quóc Huy, mã số 2305HTTB011. Mốc quan sát giao diện: 02/10/2026. Số liệu danh mục thủ tục được giữ đúng ngày của văn bản công bố.')
  fields=[('MỤC LỤC','TOC \\o "1-2" \\h \\z')]
  if not brief:fields += [('DANH MỤC BẢNG BIỂU','TOC \\h \\z \\c "Bảng"'),('DANH MỤC HÌNH VÀ SƠ ĐỒ','TOC \\h \\z \\c "Hình"')]
  for t,f in fields:
   p=self.e['cloned_caption'](116,t);p.paragraph_format.page_break_before=True;p=self.d.add_paragraph();self.e['add_field'](p,f,'Cập nhật trường trong Microsoft Word')
  if not brief:
   self.h('DANH MỤC TỪ VIẾT TẮT');self.e['table']([['Ký hiệu','Nội dung'],['TTHC','Thủ tục hành chính'],['UBND','Ủy ban nhân dân'],['UML','Ngôn ngữ mô hình hóa thống nhất'],['UC','Mã Use case của bản thiết kế mới'],['CN','Mã chức năng dùng chung'],['MR','Mã chức năng mở rộng nghiên cứu'],['MH','Mã màn hình đề xuất'],['API','Giao diện lập trình ứng dụng']])
 def finish(self):
  self.d.core_properties.author='Lê Quóc Huy';self.d.core_properties.title=self.file.stem;self.d.save(self.file)
  ref=self.e['REF'];editable={'word/document.xml','word/_rels/document.xml.rels','[Content_Types].xml','word/settings.xml','docProps/core.xml','docProps/app.xml'}
  with ZipFile(ref) as zr,ZipFile(self.file) as zf:
   data={n:zf.read(n) for n in zf.namelist()}
   for n in zr.namelist():
    if n not in editable:data[n]=zr.read(n)
  with ZipFile(self.file,'w',ZIP_DEFLATED) as z:
   for n,b in data.items():z.writestr(n,b)
  manifest={'file':str(self.file),'tables':self.e['caps'],'figures':self.e['figcaps'],'paragraphs':len(self.d.paragraphs)}
  (ROOT/'05_Doi_chieu/Kiem_tra_huong_doi_tuong_20261002'/ (self.file.stem+'_danh_muc.json')).write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8');print(self.file.name,len(manifest['tables']),len(manifest['figures']))

b=Book('Phan_tich_thiet_ke_huong_doi_tuong_Ha_Noi.docx',('Phân tích và thiết kế hướng đối tượng','Hệ thống giải quyết thủ tục hành chính Hà Nội'));b.front()
b.h('CHƯƠNG 1. ĐỐI TƯỢNG VÀ PHẠM VI NGHIÊN CỨU')
b.h('1.1. Hệ thống thực tế và các địa chỉ truy cập',2)
b.p('Đối tượng nghiên cứu là Hệ thống thông tin giải quyết thủ tục hành chính thành phố Hà Nội. Nguồn [10] ghi nhận hệ thống vận hành từ ngày 11/04/2023; tài liệu công dân [1] thể hiện tên hệ thống và các chức năng giao diện lịch sử. Địa chỉ dichvucong.hanoi.gov.vn là địa chỉ gắn với hệ thống Thành phố. Từ 01/07/2025, người dân được hướng dẫn sử dụng Cổng Dịch vụ công quốc gia theo [2]. Việc chuyển cửa truy cập công dân không đủ để kết luận hệ thống xử lý phía sau của Hà Nội đã ngừng hoạt động.')
b.tab(1,'Địa chỉ và bằng chứng sử dụng',[['Địa chỉ','Vai trò và giới hạn'],['https://dichvucong.hanoi.gov.vn/','Địa chỉ Hà Nội; khi quan sát chuyển đến cổng quốc gia'],['https://dichvucong.gov.vn/','Cửa công dân hiện được quan sát công khai; chưa đăng nhập hoặc gửi hồ sơ'],['https://ttpvhcc.hanoi.gov.vn/','Công bố hướng dẫn, quyết định, phương án và hoạt động của Trung tâm'],['Hệ thống cán bộ và kết nối nội bộ','Chưa có quyền truy cập; thiết kế phía sau được đề xuất từ quy trình công khai']])
b.h('1.2. Đơn vị đếm chức năng và quy trình',2)
b.tab(1,'Bốn phạm vi không được đếm lẫn',[['Đơn vị','Số lượng','Cách hiểu'],['Nhóm chức năng','9','Khung đối chiếu chức năng dùng chung theo [3]'],['Chức năng dùng chung','31','Được mã hóa CN01 đến CN31 trong nghiên cứu; chưa xác nhận đúng 31 mục thực tế trong tài khoản cán bộ'],['Use case thiết kế','36','31 ca truy vết chức năng chuẩn và 5 ca mở rộng phục vụ tài chính, số hóa, phản ánh, nộp lưu'],['Dòng thủ tục tại QĐ 492','2.075','Danh mục ngày 14/04/2026: 1.120 toàn trình, 921 một phần, 34 cung cấp thông tin; chưa khẳng định toàn bộ còn hiệu lực ngày 02/10/2026']])
b.p('Một chức năng có thể phục vụ hàng nghìn thủ tục. Một thủ tục lại có nhiều nhánh theo chủ thể, cơ quan, kênh, thành phần, phối hợp và ngoại lệ. Vì vậy không thể suy ra hệ thống có 2.075 quy trình duy nhất, cũng không thể dùng 31 để trả lời số thủ tục của thành phố. Số nhánh cấu hình nội bộ chưa được nguồn công khai chứng minh.')
b.h('1.3. Phương pháp và mức độ chứng minh',2)
b.p('Nguồn được chia theo thời điểm và loại bằng chứng. Ảnh công khai năm 2026 chứng minh nội dung có thể xem khi chưa đăng nhập. Ảnh trong hướng dẫn 2023 chỉ chứng minh giao diện lịch sử. Quyết định công bố chứng minh quy trình được phê duyệt trong phạm vi văn bản; không chứng minh đã thực hiện mọi bước trên phần mềm. Mô hình đề xuất được kiểm tra tính nhất quán, không được gọi là kiến trúc nội bộ đã khảo sát.')
b.p('Ký pháp được đối chiếu với [8]. Đường sống xác định đối tượng tương tác; thông điệp phải có bên gửi, bên nhận và thứ tự. Khung alt phân tách điều kiện. Hoạt động dùng nút đầu, quyết định, kết thúc; phối hợp đồng thời dùng thanh phân nhánh và hợp nhánh. Lớp thể hiện thuộc tính, thao tác và bội số. Mũi tên khái quát hóa hướng về vai trò chung. Các nhãn Giao diện, Điều khiển, Thực thể trong hình phân tích là quy ước của bản nghiên cứu, được giải thích tại chương 4.')

b.h('CHƯƠNG 2. GIAO DIỆN THỰC TẾ VÀ CÁC NHÁNH DỊCH VỤ')
b.h('2.1. Quan sát công khai ngày 02/10/2026',2)
UI=ROOT/'03_Thiet_ke/Anh_he_thong'
for f,t in [('01_cong_quoc_gia_20261002.jpg','Cổng quốc gia sau khi truy cập địa chỉ Hà Nội'),('02_tra_cuu_thu_tuc_20261002.jpg','Tra cứu thủ tục hộ tịch trên cửa công dân hiện tại'),('03_chi_tiet_trich_luc_20261002.jpg','Chi tiết công khai thủ tục 2.000635'),('04_chon_co_quan_hanoi_20261002.jpg','Chọn Hà Nội và Phường Hoàn Kiếm trước khi nộp')]:
 b.fig(2,'',t+'; ảnh quan sát 02/10/2026',UI/f)
b.p('Các ảnh trên dừng ở phần công khai; chưa thao tác gửi yêu cầu, thanh toán hoặc ký. Người dùng cần chọn đúng cơ quan trước khi xác nhận thủ tục áp dụng. Thông tin chung trên trang quốc gia và phương án riêng của Hà Nội phải được đối chiếu thay vì sao chép thành một cấu hình thống nhất.')
b.h('2.2. Giao diện lịch sử có nguồn',2)
hist={27:'Danh sách thủ tục',28:'Chi tiết thủ tục và nút nộp',29:'Kê khai thành phần hồ sơ',30:'Chọn tài liệu trong kho',31:'Kê khai người được ủy quyền',32:'Xác nhận và gửi hồ sơ',33:'Tình trạng hồ sơ sau tra cứu',34:'Mở hồ sơ của người sử dụng',36:'Cửa phản ánh và kiến nghị',38:'Gửi phản ánh'}
for page,t in hist.items():
 b.fig(2,'',t+f'; ảnh trích tài liệu [1] năm 2023, trang {page}',UI/f'lich_su_2023_trang_{page}.png')
b.p('Tất cả ảnh của mục 2.2 là tư liệu lịch sử. Tên và dữ liệu xuất hiện trong ảnh là nội dung của tài liệu nguồn, không phải hồ sơ do nghiên cứu tạo ra. Tài liệu không dùng giao diện năm 2023 làm hướng dẫn đăng nhập hiện hành, không khẳng định cơ cấu cơ quan cũ còn áp dụng.')
b.h('2.3. Các nhánh xử lý phải thiết kế riêng',2)
b.tab(2,'Nhánh dịch vụ và tác động lên thiết kế',[['Nhánh','Điểm phân biệt','Use case liên quan'],['Theo mức trực tuyến','Toàn trình; một phần; chỉ thông tin. Nhánh chỉ thông tin không mặc nhiên có chức năng gửi hồ sơ','UC03, UC05, UC22'],['Theo hệ thống có thẩm quyền','Hệ thống Thành phố hoặc hệ thống tập trung của bộ theo [9]; cần xác nhận tuyến và đầu mối','UC06, UC30, UC31'],['Theo kênh','Trực tuyến, trực tiếp, bưu chính khi thủ tục cho phép; giấy cần số hóa và giao nhận','UC12, UC18, UC34'],['Theo chủ thể','Bản thân, tổ chức, đại diện, người được ủy quyền; quyền xem khác quyền thay mặt nộp','UC05, UC18, UC29'],['Theo kết quả kiểm tra','Đủ để nhận; thiếu để bổ sung; không thể hoàn thiện; không thuộc thẩm quyền','UC12, UC13, UC17'],['Theo thẩm định','Đủ căn cứ; cần phối hợp; cần bổ sung; không giải quyết; trả chỉnh sửa','UC15, UC16'],['Theo tài chính','Không thu; phải thu; miễn giảm; thất bại; chậm phản hồi; chênh lệch; hoàn','UC32, UC33'],['Theo hậu kiểm','Kết quả đã phát hành; giao thất bại; nộp lưu được nhận hoặc trả gói','UC18, UC36']])

b.h('CHƯƠNG 3. TÁC NHÂN, Use case VÀ HƯỚNG DẪN CHỨC NĂNG')
b.h('3.1. Tác nhân và phạm vi trách nhiệm',2)
b.fig(3,'phan_cap_tac_nhan','Phân cấp vai trò cán bộ')
b.fig(3,'ca_su_dung_tong_the','Use case tổng thể theo mục tiêu')
b.p('Tác nhân là vai trò tương tác, không đồng nhất với tên cơ quan. Một cá nhân có nhiều vai trò nhưng chỉ thực hiện thao tác trong phạm vi được giao tại thời điểm thao tác. Quản trị kỹ thuật không mặc nhiên có quyền đọc hồ sơ, cấp quyền cho bản thân hoặc ký thay lãnh đạo. Các hệ thống ngoài chỉ tham gia qua giao tiếp đã được phê duyệt.')
b.tab(3,'Phân tách trách nhiệm quan trọng',[['Hành động','Vai trò chịu trách nhiệm','Điểm kiểm soát'],['Tiếp nhận','Cán bộ tiếp nhận','Thẩm quyền, thành phần, phiên bản và giấy hẹn'],['Thẩm định','Chuyên viên được phân công','Bằng chứng và nhiệm vụ phối hợp'],['Duyệt và ký','Người có thẩm quyền','Đúng bản dự thảo và chứng thư'],['Phát hành','Văn thư được giao','Số văn bản và bản ký bất biến'],['Thu, hoàn, đối soát','Cán bộ tài chính và bên thanh toán','Không dùng ảnh thanh toán để ghi nhận'],['Nộp lưu','Cán bộ lưu trữ','Gói toàn vẹn, thành phần và biên nhận'],['Cấp quyền','Quản trị được ủy quyền và người phê duyệt','Không tự duyệt quyền của bản thân']])
for g in GROUPS:
 b.h(f'3.{g+1}. Nhóm {g}: {GROUPS[g]}',2)
 items=[u for u in MODEL if u['group']==g]
 if g in [2,4]:
  for i in range(0,len(items),5):b.fig(3,f'ca_su_dung_nhom_{g}_phan_{i//5+1}',f'Use case nhóm {g}, phần {i//5+1}')
 else:b.fig(3,f'ca_su_dung_nhom_{g}',f'Use case nhóm {g}')
 for u in items:
  c=next(x for x in CONTRACT if x['uc']==u['id']);b.h(u['id']+'. '+u['name'],3)
  b.tab(3,'Đặc tả '+u['id'],[['Thành phần','Nội dung'],['Mã và mục tiêu',u['function']+'; '+u['name']],['Tác nhân chính',u['actor']],['Tiền điều kiện',u['guard']],['Đầu vào',u['inputs']],['Luồng chính','; '.join(f'{i}. {s}' for i,s in enumerate(u['steps'],1))],['Ngoại lệ',u['exception']],['Hậu điều kiện','Trả đúng phạm vi dữ liệu; không thay đổi trạng thái nghiệp vụ' if u['read_only'] else 'Kết quả đã xác nhận và nhật ký được lưu cùng giao dịch; thử lại không ghi trùng'],['Truy vết',u['screen']+'; '+u['controller']+'.'+u['operation']+'; '+u['test']+'A đến '+u['test']+('C' if u['read_only'] else 'E')]])
  b.p('Hướng dẫn thực hiện theo thiết kế: ' + ' '.join(f'Bước {i}: {s}.' for i,s in enumerate(u['steps'],1)))
  b.p(u['exception']+'.')
  b.fig(3,u['id']+'_man_hinh',u['screen']+'; bản thiết kế màn hình '+u['name'].lower())
  b.fig(3,u['id']+'_trinh_tu','Tương tác một thao tác của '+u['id'])
  b.fig(3,u['id']+'_hoat_dong','Hoạt động một thao tác của '+u['id'])
b.h('3.11. Phối hợp đồng thời và xử lý trả lại',2)
b.fig(3,'hoat_dong_phoi_hop_song_song','Hai nhiệm vụ phối hợp bắt buộc trong UC15')
b.p('Biểu đồ tương tác của mỗi ca thể hiện một thao tác tại một thời điểm, không gom toàn bộ nhiều ngày xử lý vào một lần gọi. UC13 gồm lệnh lập yêu cầu và lệnh đối chiếu bổ sung của vai trò tương ứng; UC16 gồm phê duyệt, ký và phát hành bằng các lệnh tách theo quyền. Hình tổng quát không thay cho bảng chuyển bước ở chương 4. Khi một cơ quan phối hợp chậm, tạo sự kiện giám sát và quyết định ngoại lệ; không dùng thanh hợp nhánh để giả định đã nhận ý kiến.')

b.h('CHƯƠNG 4. MÔ HÌNH LỚP, TRẠNG THÁI VÀ KIẾN TRÚC')
b.h('4.1. Trách nhiệm của lớp phân tích',2)
b.fig(4,'lop_phan_tich_tiep_nhan','Phân tách giao diện, điều khiển, thực thể và truy xuất')
b.fig(4,'lop_mien_cot_loi','Quan hệ miền cốt lõi quanh hồ sơ')
b.p('Lớp giao diện tiếp nhận dữ liệu và thể hiện lỗi, không quyết định thẩm quyền hoặc tự đổi trạng thái. Lớp điều khiển tổ chức một thao tác, xác thực phạm vi, lấy phiên bản và mở giao dịch. Thực thể giữ các bất biến của hồ sơ, kết quả, nghĩa vụ thu và nhiệm vụ phối hợp. Lớp truy xuất chỉ đọc và ghi theo điều kiện được lớp ứng dụng xác lập. Dịch vụ ngoài được bọc qua bộ chuyển đổi, không gọi trực tiếp từ thực thể miền.')
b.h('4.2. Lớp miền và quan hệ đầy đủ',2)
for g,name,keys in MAPPING['diagrams']:b.fig(4,name,f'Các lớp miền nhóm {g}: '+GROUPS[int(g)])
b.tab(4,'Ánh xạ 35 lớp miền sang dữ liệu',[['Lớp','Bảng','Trách nhiệm'],*[[MAPPING['classes'][k],k,v[0]] for k,v in SCHEMA.items()]], [2200,2400,4472])
b.p('Các hình lớp trình bày một số thuộc tính và quan hệ chính để đọc rõ. Bảng dưới liệt kê toàn bộ 62 khóa ngoại trong mô hình dữ liệu; ký hiệu 0..* ở phía lớp con biểu thị số đối tượng con của một đối tượng cha. Phía cha là 1 hoặc 0..1 theo tính bắt buộc của tham chiếu. Quan hệ lưu trữ không mặc nhiên là hợp thành: hồ sơ, tài liệu ký và nhật ký không bị xóa dây chuyền theo thao tác xóa giao diện.')
b.tab(4,'Toàn bộ quan hệ tham chiếu và bội số',[['Lớp nguồn','Thuộc tính','Lớp đích','Bội số tại đích'],*[[MAPPING['classes'][a['source']],a['field'],MAPPING['classes'][a['target']],a['target_multiplicity']+'; phía nguồn 0..*'] for a in ASSOC]], [2500,2250,2700,1622])
b.p('Từ điển 35 bảng với đầy đủ kiểu, khóa và tính bắt buộc được giữ trong 03_Thiet_ke/Tu_dien_du_lieu.json và phần thiết kế của báo cáo nghiên cứu tổng hợp. Những cột cấu trúc linh hoạt phải có lược đồ theo phiên bản; chưa được đưa dữ liệu bất kỳ vào môi trường vận hành. Quan hệ miền, quyền truy cập và vòng đời phải được thực hiện trong lớp ứng dụng, không chỉ dựa vào khóa ngoại.')
b.h('4.3. Máy trạng thái hồ sơ',2)
b.tab(4,'12 trạng thái và ý nghĩa',[['Mã','Ý nghĩa'],['NHAP','Chưa gửi; chưa tạo trách nhiệm tiếp nhận'],['CHO_TIEP_NHAN','Đã gửi, chờ kiểm tra'],['CHO_BO_SUNG','Chờ đáp ứng yêu cầu; lưu giai đoạn quay lại'],['DA_TIEP_NHAN','Đã xác nhận tiếp nhận'],['DANG_THU_LY','Đang xử lý theo phân công'],['TRINH_DUYET','Dự thảo đang chờ quyết định'],['DA_PHE_DUYET','Đúng bản đã được ký duyệt'],['DA_PHAT_HANH','Đã cấp số và phát hành'],['HOAN_THANH','Có bằng chứng giao hợp lệ'],['TU_CHOI','Không tiếp nhận theo căn cứ'],['KHONG_GIAI_QUYET','Kết luận không giải quyết theo căn cứ'],['DUNG','Có quyết định dừng được duyệt']])
for name,title in [('trang_thai_HoSo','Các nhánh tiếp nhận và kết luận'),('trang_thai_HoSo_bo_sung','Bổ sung quay lại đúng giai đoạn'),('trang_thai_HoSo_phat_hanh','Ký duyệt, phát hành và xác nhận giao')]:b.fig(4,name,title)
b.tab(4,'18 chuyển bước kiểm soát hồ sơ',[['Nguồn','Sự kiện và đích','Điều kiện','Vai trò'],*[[t['source'],t['event']+' → '+t['target'],t['guard'],t['role']] for t in MACHINE['transitions']]], [1850,2600,2922,1700])
b.p('Bốn trạng thái kết thúc không có lệnh chuyển thông thường. Đính chính, hủy văn bản, giải quyết khiếu nại hoặc mở lại phải được thiết kế thành nghiệp vụ riêng có căn cứ, không sửa trực tiếp lịch sử. Hạn xử lý là kết quả tính theo phiên bản quy tắc và lịch làm việc; không dùng trạng thái QUÁ HẠN thay cho trạng thái chuyên môn. Việc bổ sung hoặc mất kết nối không tự dừng hay tính lại hạn.')
b.h('4.4. Vòng đời các đối tượng độc lập',2)
for x,t in [('KetQua','Kết quả'),('KhoanThu','Khoản thu'),('NhiemVuPhoiHop','Nhiệm vụ phối hợp'),('ThongDiep','Thông điệp kết nối'),('GoiNopLuu','Gói nộp lưu')]:b.fig(4,'trang_thai_'+x,'Vòng đời '+t.lower())
b.tab(4,'Nhánh ngoại lệ không được suy thành trạng thái hồ sơ',[['Đối tượng','Ngoại lệ','Quy tắc xử lý'],['Khoản thu','Miễn, giảm, thu lỗi, hoàn, chênh lệch','Miễn giảm phải có căn cứ; hoàn là nghĩa vụ và phê duyệt riêng; không biến hồ sơ đã hoàn thành thành đang thụ lý'],['Kết quả','Trả chỉnh sửa; sai bản; chứng thư không hợp lệ','Bản chưa ký tạo phiên bản mới; bản đã ký không sửa; đính chính cần nghiệp vụ riêng'],['Nhiệm vụ phối hợp','Chậm trả lời; ý kiến thiếu; sai phiên bản','Theo dõi hạn nhiệm vụ; yêu cầu sửa và lưu nguồn ý kiến; không mặc nhiên đồng ý'],['Thông điệp','Trùng; khác nội dung; đảo thứ tự; phản hồi chậm','Khử trùng theo nguồn và mã; cách ly xung đột; đối soát; không lùi trạng thái hồ sơ'],['Gói nộp lưu','Thiếu thành phần; sai giá trị băm; trả gói','Giữ phiên bản đã gửi; lập bản bổ sung có truy vết; chỉ chốt khi có biên nhận']])
b.h('4.5. Gói, thành phần, cộng tác và triển khai',2)
for name,t in [('goi_he_thong','Chín gói chức năng và phụ thuộc'),('thanh_phan_he_thong','Các thành phần thực thi đề xuất'),('cong_tac_phat_hanh','Cộng tác đối tượng khi phát hành'),('trien_khai_uml','Các nút triển khai và vùng truy cập đề xuất')]:b.fig(4,name,t)
b.p('Gói tổ chức mã theo nghiệp vụ; thành phần xác định phần mềm thực thi và giao diện được cung cấp; triển khai xác định máy hoặc vùng hạ tầng chứa thành phần. Sơ đồ cộng tác đánh số thông điệp theo cùng thứ tự trách nhiệm của UC16. Gói tích hợp phụ thuộc hợp đồng nghiệp vụ; nghiệp vụ không phụ thuộc nhà cung cấp chữ ký hay thanh toán cụ thể. Hình hạ tầng không công bố địa chỉ, cấu hình hoặc mô hình kết nối thực của Hà Nội.')
b.tab(4,'Phân bố thực thi và giao tiếp',[['Vùng','Thành phần','Giao tiếp và kiểm soát'],['Cửa công dân','Giao diện, cổng tiếp nhận','HTTPS; xác thực qua cơ chế được phê duyệt; kiểm tra giới hạn truy cập'],['Nghiệp vụ','Dịch vụ hồ sơ, quyền, quy trình','HTTPS nội bộ; định danh dịch vụ; kiểm tra quyền tại mỗi thao tác'],['Dữ liệu','Cơ sở dữ liệu, kho tệp, hàng đợi','Kết nối có mã hóa; tài khoản tối thiểu; giao dịch và sao lưu'],['Tích hợp','Bộ chuyển đổi đối tác','Hợp đồng có phiên bản; xác nhận nguồn; khóa chống lặp; đối soát'],['Quản trị','Giám sát, nhật ký, triển khai','Kênh quản trị riêng; phê duyệt thay đổi; che bí mật và dữ liệu cá nhân']])
b.tab(4,'Ma trận phụ thuộc các gói đề xuất',[['Gói','Phụ thuộc được phép','Lý do'],['1','Lõi miền và hợp đồng chung','Quyền, chủ thể và cơ quan'],['2','1','Quyền quản trị, danh mục và hiệu lực'],['3','1 và hợp đồng kết quả của lõi miền','Thẩm quyền ký; không phụ thuộc nhà cung cấp cụ thể'],['4','1, 2, 3, 8','Quyền, quy trình, chữ ký và tài liệu hợp lệ'],['5','1, 4','Thông báo, hỗ trợ và tra cứu theo hồ sơ'],['6','1 và mô hình đọc của 4','Báo cáo dùng bản dữ liệu có thời điểm chốt'],['7','1, 4','Chỉ đạo và giám sát trách nhiệm'],['8','1, 2 và lõi miền','Quyền khai thác, phân loại và phiên bản tài liệu'],['9','1 và giao diện dịch vụ của 4','Bộ chuyển đổi thực hiện hợp đồng được nghiệp vụ cung cấp']])
b.p('Lõi miền và hợp đồng chung không phụ thuộc lớp giao diện, cơ sở dữ liệu hoặc nhà cung cấp ngoài. Hình gói minh họa ba phụ thuộc để giữ đường nối rõ; ma trận ghi đầy đủ quy tắc đề xuất. Gói 6 dùng mô hình đọc, không gọi thao tác đổi trạng thái. Gói 9 thực hiện giao diện trừu tượng của nghiệp vụ; gói 4 không nhập mã nhà cung cấp của gói 9.')

b.h('CHƯƠNG 5. HƯỚNG DẪN THEO THỦ TỤC CỤ THỂ')
b.h('5.1. Thư viện 2.075 hồ sơ thủ tục',2)
b.p('Thư viện tại 07_Huong_dan/Thu_tuc_theo_QD_492 có một tệp cho mỗi dòng của ba phụ lục [4]. Trang Tra_cuu_danh_muc.html cho phép tìm theo tên, mã, cơ quan và lĩnh vực. Mỗi hồ sơ có mức cung cấp trực tuyến, trang nguồn và hướng dẫn tiếp cận theo mức. Đây là phủ danh mục lịch sử, chưa phải 2.075 hướng dẫn chuyên biệt đã xác minh đầy đủ hiện hành.')
b.tab(5,'Mức cung cấp và phạm vi hướng dẫn',[['Mức','Số dòng','Hướng dẫn tương ứng'],['Toàn trình','1.120','Tra cứu phiên bản, kê khai, chọn tài liệu, xác nhận gửi, theo dõi và nhận kết quả theo thủ tục'],['Một phần','921','Các bước điện tử và bước cần thực hiện trực tiếp hoặc qua bưu chính được xác định từ chi tiết thủ tục'],['Thông tin','34','Đọc thông tin và chọn kênh hợp lệ; không suy ra có chức năng gửi trực tuyến']])
b.p('Một số mã trong bản phụ lục có cách ghi không theo khuôn phổ biến. Thư viện giữ nguyên chữ của nguồn và đánh dấu cần xác minh, không tự thêm dấu hoặc chữ số. Số thứ tự hồ sơ thư viện là mã kỹ thuật độc lập với số thứ tự in, nhằm tránh mất dòng khi phụ lục in trùng số. Các trường thành phần, số lượng, mẫu, phí, hạn, điều kiện và kết quả chưa có nguồn chi tiết được ghi rõ chưa xác minh.')
b.tab(5,'Điều kiện để một hướng dẫn chuyên biệt được coi là đầy đủ',[['Nội dung','Bằng chứng phải có'],['Hiệu lực','Quyết định công bố hoặc cập nhật, ngày áp dụng và phạm vi cơ quan'],['Chủ thể và thẩm quyền','Người có quyền yêu cầu, quan hệ đại diện, cơ quan xử lý hiện hành'],['Hồ sơ và biểu mẫu','Danh sách thành phần, số lượng, mẫu và bản phải xuất trình'],['Thời hạn và khoản thu','Quy tắc mốc nhận, ngày làm việc, ngoại lệ, miễn giảm và căn cứ'],['Luồng và các nhánh','Trực tuyến, trực tiếp, bưu chính, bổ sung, từ chối, phối hợp, trả kết quả'],['Ảnh và minh chứng','Ảnh đúng thời điểm và phiên bản, hoặc bản thiết kế ghi rõ là đề xuất'],['Kiểm tra đối chiếu','Hai người hoặc một lần rà soát độc lập đối chiếu với nguồn; chưa áp dụng trong nghiên cứu cho toàn bộ danh mục']])
b.h('5.2. Cấp bản sao trích lục hộ tịch, bản sao giấy khai sinh',2)
b.p('Mã thủ tục là 2.000635. Nghiên cứu có hai lớp nguồn: trang công khai [7] quan sát ngày 02/10/2026 và phương án tái cấu trúc tại [5] ngày 24/12/2025. Chọn Hà Nội và cơ quan cụ thể trên cửa công dân là bước xác định phạm vi, chưa chứng minh toàn bộ thông tin chung của trang áp dụng đúng phương án địa phương.')
b.tab(5,'Hướng dẫn tiếp cận và kiểm soát cho thủ tục hộ tịch',[['Bước','Người yêu cầu','Cơ quan và kiểm soát'],['1. Chọn','Tìm 2.000635; chọn Hà Nội và cơ quan đúng thẩm quyền','Đối chiếu phiên bản, nguồn hộ tịch và tuyến dữ liệu'],['2. Chuẩn bị','Đọc thành phần, điều kiện đại diện và mẫu được công bố; kê khai chính xác sự kiện cần trích lục','Không yêu cầu thêm giấy tờ ngoài quy định; xác định dữ liệu có thể khai thác'],['3. Gửi','Xem lại tờ khai, tài liệu, kênh trả; lưu mã giao dịch','Kiểm tra quan hệ chủ thể, khử trùng và trả biên nhận'],['4. Kiểm tra','Đọc yêu cầu bổ sung hoặc thông báo tiếp nhận','Bổ sung có nội dung và căn cứ; không nhầm với kết luận từ chối'],['5. Thẩm định','Phản hồi nội dung được yêu cầu trong phạm vi quyền','Kiểm tra dữ liệu nguồn; lỗi kết nối không chứng minh sự kiện hộ tịch không tồn tại'],['6. Xác nhận và thu','Đọc bản dự thảo khi quy trình áp dụng yêu cầu; kiểm tra khoản thu và miễn giảm','Áp dụng quy tắc của phiên bản địa phương; đối soát đúng khoản thu'],['7. Nhận','Kiểm tra thông tin trích lục; nhận bản được phát hành qua kênh đã chọn','Ký, phát hành và lưu chứng cứ giao; xử lý sai sót qua nghiệp vụ có căn cứ']])
b.tab(5,'Những khác biệt phải xác nhận trước cấu hình',[['Điểm đối chiếu','Trang quốc gia quan sát','Yêu cầu trước khi áp dụng Hà Nội'],['Cơ quan','Có lựa chọn địa phương; nguồn công bố chung','Xác nhận cơ quan lưu sổ và phân tuyến theo phương án được duyệt'],['Khoản thu','Trang chung hiển thị mức 8.000 đồng','Chưa lấy mức chung làm khoản thu mặc định mọi kênh tại Hà Nội; đối chiếu miễn giảm và quyết định còn hiệu lực'],['Bản dự thảo','Trang có hướng dẫn xác nhận dự thảo trong thời gian tối đa một ngày','Xác định bước này có thuộc cấu hình địa phương hiện hành không'],['Hạn','Thông tin chung có quy tắc xử lý theo mốc nhận và nhánh xác minh','Đối chiếu hạn pháp lý, các bước nội bộ và nguồn dữ liệu của phiên bản Hà Nội'],['Tái cấu trúc','Thông tin chung chưa chứng minh toàn bộ phương án [5]','Giữ hai phiên bản nguồn; cần đầu mối nghiệp vụ xác nhận mô hình áp dụng']])
b.h('5.3. Cấp bản sao từ sổ gốc',2)
b.p('Mã thủ tục là 2.000908. [6] trang 65 đến 69 công bố quy trình tại cấp xã, các kênh trực tiếp, trực tuyến và bưu chính, không thu phí. Mốc giải quyết theo ngày nhận và trường hợp nhận sau 15 giờ phải được phân biệt với phân bổ thao tác nội bộ. Các bước nội bộ phân bổ 2, 3, 2, 1 giờ không được chuyển thành quy tắc mọi hồ sơ đều có hạn pháp lý tám giờ.')
b.tab(5,'Thành phần và điều kiện theo [6]',[['Nội dung','Quy định được đối chiếu'],['Giấy tờ nhận diện','Một loại giấy tờ nhận diện còn giá trị theo danh sách tại mục 3.2. Không yêu cầu nộp giấy tờ nhận diện khi cơ quan khai thác được thông tin căn cước từ cơ sở dữ liệu dân cư hoặc VNeID'],['Quan hệ đại diện hoặc thân nhân','Giấy tờ chứng minh quan hệ khi yêu cầu thay mặt hoặc thuộc trường hợp thân nhân, thừa kế được quy định. Không yêu cầu nộp nếu cơ quan khai thác được thông tin khai sinh, kết hôn trong cơ sở dữ liệu hộ tịch điện tử'],['Số lượng','Một bộ hồ sơ'],['Điều kiện cấp','Có sổ gốc và nội dung bản sao đúng thông tin của sổ; nếu không tìm thấy sổ hoặc nội dung, cơ quan trả lời có căn cứ'],['Phân biệt thủ tục','Yêu cầu bản sao trích lục hộ tịch, bản sao giấy khai sinh thực hiện theo thủ tục hộ tịch, không áp dụng thay bằng 2.000908'],['Hạn','Trong ngày hoặc ngày làm việc tiếp theo nếu nhận sau 15 giờ. Mốc tính theo thời điểm nhận đủ hồ sơ hợp lệ tương ứng kênh nhận'],['Phí','Không theo mục 3.6; không đồng nhất phí thủ tục với cước bưu chính nếu người yêu cầu chọn dịch vụ chuyển phát']])
b.tab(5,'Hướng dẫn thủ tục cấp bản sao từ sổ gốc',[['Bước','Thực hiện','Điểm kiểm tra'],['1. Chọn thủ tục','Tìm đúng mã, cơ quan cấp xã giữ sổ gốc và kênh được phép','Không chọn nhầm bản sao trích lục hộ tịch hoặc chứng thực bản sao'],['2. Chuẩn bị','Đọc và chuẩn bị thành phần theo [6], quan hệ người yêu cầu và tài liệu cần xuất trình','Không tự quy định một bộ giấy tờ chung cho mọi trường hợp đại diện'],['3. Nộp','Trực tiếp, trực tuyến hoặc bưu chính theo công bố; lưu bằng chứng nộp','Số hóa giấy theo quyền; không làm phát sinh phí trái công bố'],['4. Tiếp nhận','Kiểm tra thành phần và hướng dẫn thiếu bằng văn bản có căn cứ','Ghi thời điểm thực tế, áp dụng mốc 15 giờ khi thuộc quy định'],['5. Đối chiếu sổ','Chuyên viên kiểm tra thông tin trong sổ gốc, lập bản sao','Không dùng lỗi truy cập như kết luận không có sổ'],['6. Duyệt và phát hành','Lãnh đạo và văn thư thực hiện phần việc theo quy trình nội bộ','Đúng người có quyền, đúng phiên bản, bản ký bất biến'],['7. Trả','Nhận qua kênh được công bố; kiểm tra bản sao và thông tin nhận','Lưu chứng cứ giao, kết thúc hồ sơ và lập gói lưu khi đủ điều kiện']])
b.p('Hai thủ tục trên là trường hợp đối chiếu chuyên sâu có văn bản quy trình. Chúng không thay thế hướng dẫn chuyên biệt của các thủ tục còn lại. Trước khi hướng dẫn người dân thực hiện thật hoặc đưa cấu hình vào vận hành, cần kiểm tra văn bản thay thế, thông tin chi tiết đúng cơ quan và ngày áp dụng.')

b.h('CHƯƠNG 6. ĐẶC TẢ CHUYỂN SANG LẬP TRÌNH')
b.h('6.1. Hợp đồng thao tác và dữ liệu',2)
b.p('Hợp đồng 36 thao tác được lưu tại 03_Thiet_ke/Huong_doi_tuong/Hop_dong_36_thao_tac.json. Địa chỉ trong bảng là giao tiếp đề xuất của ứng dụng nghiên cứu, không phải địa chỉ giao tiếp Hà Nội đang vận hành. Thao tác đọc dùng GET; lệnh thay đổi dùng POST và khóa chống lặp. Mọi hợp đồng kiểm tra vai trò và phạm vi phía máy chủ, không dựa vào việc ẩn nút trên giao diện.')
for u,c in zip(MODEL,CONTRACT):
 b.tab(6,'Hợp đồng '+u['id'],[['Thành phần','Đặc tả'],['Thao tác',c['method']+' '+c['path']],['Thực hiện',u['controller']+'.'+c['operationId']+'; vai trò '+c['role']],['Trường dữ liệu','; '.join(f+': '+v['type']+('/'+v['format'] if 'format' in v else '') for f,v in c['requestSchema']['properties'].items())],['Bắt buộc',', '.join(c['requestSchema']['required'])],['Điều kiện',c['guard']],['Thành công','Mã 200; maTuongQuan, duLieu, phienBanMoi; chỉ sau xác nhận đọc hoặc ghi'],['Lỗi','400 sai dữ liệu; 401 chưa xác thực; 403 sai quyền; 404 ngoài phạm vi tìm; 409 xung đột; 422 chưa đạt điều kiện; 503 chưa sẵn sàng'],['Lặp yêu cầu',c['idempotency']]])
b.p('Trường đối tượng và danh sách cấu trúc phải có lược đồ chuyên biệt đã phê duyệt; hợp đồng hiện tại mới xác định khung kiểu. Cần bổ sung lược đồ tờ khai từng thủ tục, giới hạn tệp được phê duyệt, chữ ký và giao tiếp thực của đối tác trước tích hợp sản xuất. Việc trả mã 200 trong hợp đồng không chứng minh có phần mềm đã chạy.')
b.h('6.2. Thuật toán chuyển bước và giao dịch',2)
phases=json.loads((BASE/'Lenh_phan_pha.json').read_text('utf-8'))
b.tab(6,'Chín lệnh phân pha và quyền thực hiện',[['Ca và lệnh','Vai trò','Trạng thái','Điều kiện'],*[[p['uc']+'; '+p['operation'],p['role'],p['source']+' → '+p['target'],p['rule']] for p in phases]],[2300,1800,2600,2372])
b.p('UC13 và UC16 là mục tiêu nghiệp vụ nhiều vai trò. Không cho một người dùng gọi toàn bộ các pha. Người yêu cầu gửi bổ sung chỉ ghi tài liệu; cán bộ đối chiếu mới chuyển giai đoạn. Người lãnh đạo duyệt bản dự thảo; xác nhận chữ ký hợp lệ mới chuyển trạng thái hồ sơ; văn thư thực hiện lệnh phát hành. Chín lệnh phân pha giải thích trách nhiệm chi tiết, không cộng thành chín Use case mới.')
b.p('Bước 1 xác thực người hoặc dịch vụ gọi. Bước 2 lọc phạm vi cơ quan và quan hệ hồ sơ ngay khi đọc. Bước 3 tìm khóa yêu cầu theo người gọi và nội dung băm; nếu đã có cùng nội dung thì trả kết quả cũ, khác nội dung thì báo xung đột. Bước 4 kiểm tra phiên bản mong đợi và điều kiện của đúng bản quy trình. Bước 5 tạo thay đổi miền, sự kiện nhật ký và thông điệp chờ gửi trong cùng giao dịch. Bước 6 xác nhận lưu rồi mới trả thành công. Tiến trình gửi ngoài đọc hàng đợi sau khi giao dịch đã xác nhận; không khóa hồ sơ chờ một đối tác phản hồi nhiều phút.')
b.tab(6,'Ràng buộc cần thực hiện và chứng minh',[['Vấn đề','Ràng buộc','Bằng chứng nghiệm thu'],['Gửi đồng thời','Cập nhật có điều kiện theo phiên bản; chỉ một lệnh thắng','Hai lệnh cùng phiên bản không cùng ghi thành công'],['Gửi lặp','Khóa duy nhất gồm phạm vi người gọi và mã yêu cầu; nội dung được băm','Gửi lại không tăng số hồ sơ, khoản thu hoặc văn bản'],['Phân công','Một phân công hiện hành; đổi người cùng giao dịch kết thúc bản cũ','Không có hai người chịu trách nhiệm chính cùng thời điểm'],['Ký','Kiểm tra đúng tệp và chứng thư trước khi gắn kết quả','Tệp khác băm không được phát hành'],['Nhận sự kiện','Nguồn và mã là duy nhất; thứ tự cũ không ghi lùi','Sự kiện trùng hoặc đảo thứ tự không đổi sai trạng thái'],['Dữ liệu người dùng','Lọc quyền trước đếm, tìm kiếm và kết xuất','Không suy ra hồ sơ ngoài quyền qua tổng số'],['Lưu trữ','Gói có danh mục, phiên bản và băm; biên nhận đúng gói','Tệp thiếu hoặc bị đổi bị phát hiện']])
b.h('6.3. Cấu hình theo phiên bản thủ tục',2)
b.p('Mỗi phiên bản thủ tục phải có quyết định, hiệu lực, cơ quan, thành phần, mẫu, quy tắc hạn, khoản thu, tuyến xử lý và quy tắc ký. Hồ sơ chốt phiên bản ngay lúc gửi hoặc tiếp nhận theo chính sách đã được nghiệp vụ xác nhận. Công bố bản mới không sửa ngầm hồ sơ đang xử lý. Nếu chuyển đổi hồ sơ cũ được phép, phải lưu căn cứ, ánh xạ trạng thái, kết quả kiểm tra và người phê duyệt.')
b.tab(6,'Bảng cấu hình cần hoàn thiện trước lập trình một thủ tục',[['Cấu hình','Kiểu và kiểm tra'],['Thông tin phiên bản','Định danh, mã quốc gia nguyên bản, số quyết định, ngày bắt đầu và kết thúc; khoảng hiệu lực không chồng lấn trong cùng phạm vi'],['Tờ khai và thành phần','Kiểu từng trường, bắt buộc theo nhánh chủ thể, số lượng, định dạng, mẫu, nguồn có thể tái sử dụng'],['Quy trình','Bước, vai trò, trạng thái, sự kiện, điều kiện và nhiệm vụ song song; có đường kết thúc hợp lệ'],['Hạn','Đơn vị, mốc bắt đầu, lịch làm việc, mốc trong ngày, nhánh xác minh, quy tắc bổ sung có căn cứ'],['Khoản thu','Số tiền nguyên đơn vị đồng, đối tượng, kênh, miễn giảm, thời điểm thu, hoàn và chứng từ'],['Kết quả','Mẫu, người duyệt, người ký, số văn bản, kênh giao và bằng chứng'],['Kết nối','Phiên bản hợp đồng, nguồn dữ liệu, mã tương quan, chữ ký, thời gian chờ, thử lại và đối soát']])
b.h('6.4. Mức độ sẵn sàng và giới hạn bàn giao',2)
b.p('Bộ hồ sơ đủ để bắt đầu xây dựng ứng dụng nghiên cứu cho các thao tác dùng chung, có dữ liệu giả lập và các kết nối được mô phỏng rõ ràng. Chưa đủ để sao chép đầy đủ hệ thống thực đang vận hành hoặc đưa 2.075 thủ tục vào sản xuất. Phần còn thiếu gồm quyền khảo sát cán bộ, cấu hình thực từng thủ tục, hợp đồng đối tác, mẫu tờ khai chi tiết, dữ liệu kiểm thử được cho phép và xác nhận quy trình địa phương hiện hành. Nghiên cứu không có yêu cầu tạo phần mềm chạy trong lần bàn giao này.')

b.h('CHƯƠNG 7. TRIỂN KHAI, KIỂM THỬ, VẬN HÀNH VÀ QUẢN TRỊ')
b.h('7.1. Lộ trình triển khai đề xuất',2)
b.tab(7,'Các giai đoạn và điều kiện chuyển tiếp',[['Giai đoạn','Công việc','Điều kiện kết thúc'],['Chuẩn bị','Chốt phạm vi, phiên bản nguồn, vai trò và dữ liệu được phép','Nghiệp vụ phê duyệt cấu hình thử nghiệm'],['Xây dựng nền','Quyền, danh mục, hồ sơ, phiên bản, nhật ký, kho và hàng đợi','Kiểm thử bất biến và phục hồi dữ liệu đạt'],['Hai thủ tục mẫu','Cấu hình riêng hộ tịch và bản sao từ sổ gốc; không dùng chung phí, hạn','Đối chiếu từng bước với quy trình được phê duyệt'],['Thí điểm','Môi trường riêng; kết nối mô phỏng hoặc đối tác cho phép','Không tồn tại lỗi làm sai thẩm quyền, mất hồ sơ hoặc thu trùng'],['Mở rộng','Nạp từng thủ tục đã xác minh; đào tạo và giám sát','Đủ hướng dẫn, cấu hình và bằng chứng nghiệm thu từng thủ tục'],['Vận hành','Giám sát, sao lưu, phục hồi, quản trị thay đổi','Có người trực, quy trình sự cố và lịch kiểm tra được duyệt']])
b.h('7.2. Kiểm thử và bằng chứng',2)
b.p(f"Bộ kiểm thử hướng đối tượng gồm {CHECK['test_cases']} ca dự kiến, truy vết 36 Use case: luồng đạt, không đạt điều kiện, sai phạm vi và với lệnh thay đổi có thêm gửi lặp, xung đột phiên bản. Tất cả ca chưa thực hiện. 11 kiểm tra dữ liệu mô hình đã chạy kiểm tra tính duy nhất, tham chiếu bảng, ca đọc, khóa ngoại và tính tới được của máy trạng thái; kết quả này không thay cho kiểm thử phần mềm. Bộ 95 ca của báo cáo tổng hợp vẫn là kế hoạch riêng, không cộng thành số ca đã đạt.")
b.tab(7,'Nhóm kiểm thử bắt buộc khi có phần mềm',[['Nhóm','Tình huống','Tiêu chí'],['Nghiệp vụ','Đủ, thiếu, từ chối, dừng, trả chỉnh sửa, nhiều cơ quan','Đúng căn cứ, vai trò và trạng thái'],['Đồng thời','Hai chuyên viên, hai lần gửi, hai phản hồi thanh toán','Không ghi đè, trùng hồ sơ hoặc trùng tiền'],['Tích hợp','Mất kết nối, lặp, đảo thứ tự, chữ ký sai','Không ghi nhận dữ liệu lỗi là kết quả hợp lệ'],['An toàn','Truy cập hồ sơ người khác, đổi cơ quan, tệp độc hại','Từ chối trước trả dữ liệu; cách ly tệp và nhật ký cần thiết'],['Khả năng tiếp cận','Bàn phím, phóng to, nhãn lỗi, đọc bằng công cụ hỗ trợ','Thao tác và thông báo hiểu được, không chỉ dựa vào màu'],['Hiệu năng','Kỳ báo cáo, giờ nộp cao, kho tệp lớn','Đạt mục tiêu được phê duyệt trên tải và dữ liệu thử'],['Phục hồi','Mất nút, mất tệp, khôi phục bản sao, hàng đợi gửi lại','Đối chiếu toàn vẹn và không nhân đôi sự kiện'],['Chấp nhận','Cán bộ thực hiện đủ nhánh hai thủ tục mẫu','Có biên bản, nguồn phiên bản và hồ sơ thử được phép']])
b.h('7.3. Vận hành và xử lý sự cố',2)
b.p('Giám sát tách thời gian phản hồi, lỗi kỹ thuật, độ trễ hàng đợi, hồ sơ đến hạn, phản hồi phối hợp và chênh lệch tài chính. Không dùng trạng thái máy chủ ổn định để kết luận hồ sơ đang được giải quyết đúng hạn. Khi đối tác lỗi, ghi mã tương quan, dừng khẳng định thành công và giữ trách nhiệm xử lý tại đầu mối; tiếp tục hoạt động nội bộ theo phương án được phê duyệt.')
b.tab(7,'Quy trình sự cố có trách nhiệm',[['Bước','Thực hiện','Bằng chứng'],['Phát hiện','Tiếp nhận cảnh báo hoặc phản ánh; xác định phạm vi','Mã sự cố, thời điểm, dịch vụ và số hồ sơ bị ảnh hưởng'],['Khoanh vùng','Kiểm tra quyền, phiên bản, giao dịch và đối tác','Nhật ký đã che dữ liệu nhạy cảm'],['Duy trì','Áp dụng phương án dự phòng được duyệt; ghi nhận hồ sơ tiếp nhận thay thế','Danh sách bàn giao và hạn theo căn cứ'],['Khôi phục','Khôi phục dịch vụ, kiểm tra dữ liệu, chạy đối soát','Không mất hoặc nhân đôi hồ sơ, tiền, chữ ký'],['Đóng','Đầu mối nghiệp vụ xác nhận; thông báo theo trách nhiệm','Biên bản, nguyên nhân và thay đổi phòng ngừa']])
b.h('7.4. Quản trị dữ liệu, thay đổi và chất lượng',2)
b.p('Chủ quản nghiệp vụ phê duyệt danh mục và quy trình; chủ quản dữ liệu quyết định phạm vi khai thác; đơn vị vận hành quản lý dịch vụ và phục hồi; đầu mối an toàn kiểm soát quyền, sự kiện và tệp; cán bộ lưu trữ kiểm tra hạn bảo quản và gói nộp lưu. Những vai trò này phải được giao bằng căn cứ tổ chức thực tế trước vận hành.')
b.tab(7,'Chỉ số, mẫu số và hạn chế diễn giải',[['Chỉ số','Cách xác định','Cảnh báo'],['Đúng hạn','Số hồ sơ kết thúc đúng hạn trên tập hồ sơ kết thúc trong kỳ đã chốt','Không trộn ngày nhận và ngày trả; công bố quy tắc loại trừ'],['Bổ sung','Số hồ sơ có ít nhất một yêu cầu bổ sung trên tập hồ sơ tiếp nhận','Tách số lần và số hồ sơ; không kết luận lỗi cán bộ từ tỷ lệ đơn lẻ'],['Tái sử dụng','Hồ sơ thực sự dùng tài liệu hợp lệ đã có trên tập hồ sơ có khả năng dùng lại','Có chứng cứ nguồn và quyền; không đếm chỉ vì mở kho'],['Đồng bộ','Thông điệp được bên nhận xác nhận áp dụng trên tập phải trao đổi','Đã gửi hoặc có biên nhận kỹ thuật chưa đủ'],['Thu và hoàn','Khoản thu, giao dịch, chứng từ, kỳ đã đối soát','Không cộng giao dịch lặp hoặc tiền đã hoàn vào thu ròng'],['Phục hồi','Kết quả diễn tập theo mục tiêu được duyệt','Mục tiêu và kết quả đo khác nhau; chưa có diễn tập trong nghiên cứu']])
b.h('TÀI LIỆU THAM KHẢO')
for code,title,url in SOURCES:b.p('['+code+'] '+title+'. '+url)
b.h('PHỤ LỤC. TỆP BÀN GIAO VÀ NỘI DUNG CÒN THIẾU')
b.tab('A','Đường dẫn tương đối trong thư mục nghiên cứu',[['Tệp hoặc thư mục','Nội dung'],['03_Thiet_ke/Huong_doi_tuong','36 ca, 35 lớp, 62 quan hệ, máy trạng thái, hợp đồng và 168 ca kiểm thử dự kiến'],['03_Thiet_ke/Huong_doi_tuong/So_do','Bản ảnh để đọc và bản véc tơ để chỉnh sửa sơ đồ'],['03_Thiet_ke/Anh_he_thong','4 ảnh công khai 2026 và 10 ảnh nguồn lịch sử 2023'],['07_Huong_dan/Chuc_nang_dung_chung','36 hướng dẫn theo bản thiết kế'],['07_Huong_dan/Thu_tuc_theo_QD_492','2.075 hồ sơ hướng dẫn tiếp cận, danh mục, trang tra cứu và nguồn theo trang'],['07_Huong_dan/Thu_tuc_phan_tich_sau','Hướng dẫn chuyên sâu theo hai thủ tục đã phân tích']])
b.p('Trạng thái cần tiếp tục: chưa xác minh đầy đủ chi tiết và hiệu lực hiện hành của 2.075 thủ tục; chưa có ảnh tài khoản cán bộ hoặc thực hiện nộp, ký, thanh toán; chưa kiểm thử phần mềm; chưa có lược đồ đầy đủ tờ khai cho toàn bộ thủ tục. Bản thiết kế không tuyên bố đạt 100% mọi yêu cầu của hệ thống thực.')
b.finish()


# Chỉ xuất báo cáo phân tích và thiết kế.
