 'use client';
import React, {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api,errorMessage} from '@/lib/api';
import {useAuthStore} from '@/lib/auth-store';
import {Button,Input,Select,Textarea} from '@/components/ui/primitives';
import {useToast} from '@/components/ui/toaster';
import {MarkdownViewer} from '@/components/common/markdown-viewer';
type Row=Record<string,any>;
export default function KnowledgePage(){
 const roles=useAuthStore(s=>s.user?.roles??[]),priv=roles.some(r=>['ADMIN','KM_MANAGER'].includes(r)); const params=useSearchParams();const [articleId,setArticleId]=useState(params.get('article')??''); const [spaceId,setSpaceId]=useState('');const [busy,setBusy]=useState(false);const qc=useQueryClient(),toast=useToast();
 const spaces=useQuery<Row[]>({queryKey:['knowledge-spaces'],queryFn:async()=>{const d=(await api.get('/spaces')).data;return Array.isArray(d)?d:d.items;}});
 const articles=useQuery<Row[]>({queryKey:['knowledge-articles',spaceId],queryFn:async()=>(await api.get(`/spaces/${spaceId}/articles`,{params:{limit:100}})).data.items,enabled:!!spaceId});
 const detail=useQuery<Row>({queryKey:['knowledge-detail',articleId],queryFn:async()=>(await api.get(`/articles/${articleId}`)).data,enabled:!!articleId});
 const versions=useQuery<Row[]>({queryKey:['knowledge-versions',articleId],queryFn:async()=>(await api.get(`/articles/${articleId}/versions`)).data,enabled:!!articleId});
 const pending=useQuery<Row[]>({queryKey:['knowledge-pending'],queryFn:async()=>{const d=(await api.get('/reviews/pending')).data;return Array.isArray(d)?d:d.items;},enabled:priv});
 async function act(url:string,data:Row={},method='post'){setBusy(true);try{const res=await api.request({url,data,method});await qc.invalidateQueries();toast('Đã cập nhật tri thức','success');return res.data;}catch(e){toast(errorMessage(e),'error');}finally{setBusy(false);}}
 const cls='rounded-lg border p-4 space-y-3';
 return <div className="space-y-5"><h1 className="text-2xl font-semibold">Tri thức & bài viết</h1><p className="text-sm text-muted-foreground">Bản thảo → trình duyệt → công bố. Mỗi lần sửa lưu một phiên bản; phạm vi không gian quyết định quyền đọc.</p>
 {priv&&<form className={cls} onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());void act('/spaces',d);}}><h2 className="font-medium">Tạo không gian</h2><Input name="name" placeholder="Tên không gian" required/><Input name="description" placeholder="Mục đích và phạm vi"/><Select name="visibility"><option value="PUBLIC">Toàn bộ người dùng đã đăng nhập</option><option value="RESTRICTED">Thành viên được cấp quyền</option><option value="PRIVATE">Riêng tư</option></Select><Button disabled={busy}>Tạo không gian</Button></form>}
 <Select value={spaceId} onChange={e=>setSpaceId(e.target.value)}><option value="">Chọn không gian</option>{spaces.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select>
 {spaceId&&<form className={cls} onSubmit={async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const a=await act(`/spaces/${spaceId}/articles`,d);if(a?.id)setArticleId(a.id);}}><h2 className="font-medium">Biên soạn bản thảo</h2><Input name="title" minLength={3} required placeholder="Tiêu đề"/><Input name="summary" placeholder="Tóm tắt"/><Textarea name="contentMd" rows={8} required placeholder="Nội dung Markdown: mục đích, phạm vi, các bước, ngoại lệ, biểu mẫu, nguồn và người chịu trách nhiệm"/><Button disabled={busy}>Lưu bản thảo</Button></form>}
 <div className="grid md:grid-cols-2 gap-4"><div className="space-y-3">{articles.data?.map(a=><button key={a.id} className="w-full text-left rounded-lg border p-3" onClick={()=>setArticleId(a.id)}><strong>{a.title}</strong><p className="text-sm">{a.status} · {a.summary}</p></button>)}{priv&&pending.data?.length?<div className={cls}><h2 className="font-medium">Bài chờ duyệt</h2>{pending.data.map(a=><button className="block underline" key={a.id} onClick={()=>setArticleId(a.id)}>{a.title}</button>)}</div>:null}</div>
 {detail.data&&<div className={cls}><h2 className="text-xl font-semibold">{detail.data.title}</h2><p className="text-sm">{detail.data.status} · phiên bản {detail.data.versionNo}</p><MarkdownViewer content={detail.data.contentMd??''}/><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>{const contentMd=prompt('Nội dung bản sửa',detail.data?.contentMd??'');if(contentMd)void act(`/articles/${articleId}`,{contentMd,changeNote:'Cập nhật từ kho tri thức'},'patch');}}>Lưu bản sửa</Button>{detail.data.status==='DRAFT'&&<Button disabled={busy} onClick={()=>act(`/articles/${articleId}/submit`)}>Trình duyệt</Button>}{priv&&detail.data.status==='PENDING_REVIEW'&&<><Button disabled={busy} onClick={()=>act(`/articles/${articleId}/review`,{action:'APPROVE',comment:'Đã kiểm tra nội dung và nguồn'})}>Phê duyệt</Button><Button variant="outline" disabled={busy} onClick={()=>{const comment=prompt('Nội dung cần sửa');if(comment)void act(`/articles/${articleId}/review`,{action:'REQUEST_CHANGES',comment});}}>Yêu cầu sửa</Button></>}</div><h3 className="font-medium">Lịch sử phiên bản</h3>{versions.data?.map(v=><div className="border-t py-2" key={v.id}><p>v{v.versionNo} · {v.author?.fullName} · {v.changeNote}</p><details><summary>Xem nội dung bản này</summary><MarkdownViewer content={v.contentMd??''}/></details><Button variant="outline" size="sm" disabled={busy} onClick={()=>act(`/articles/${articleId}/versions/${v.versionNo}/restore`)}>Khôi phục thành bản mới</Button></div>)}</div>}
 </div>{[spaces.error,articles.error,detail.error,pending.error].filter(Boolean).map((e,i)=><p key={i} className="text-destructive">{errorMessage(e)}</p>)}</div>;
}
