import { PersonnelEffectsService } from './personnel-effects.service';
describe('Effective personnel decisions',()=>{
 const today=new Date('2026-10-04T00:00:00Z');
 function setup(action:any){const tx:any={personnelAction:{findUniqueOrThrow:jest.fn().mockResolvedValue(action),updateMany:jest.fn().mockResolvedValue({count:1})},user:{findUniqueOrThrow:jest.fn().mockResolvedValue({id:'employee'}),update:jest.fn()},refreshToken:{updateMany:jest.fn()},faceEmbedding:{updateMany:jest.fn()},contract:{updateMany:jest.fn()},hrmsLifecycleEvent:{updateMany:jest.fn()},auditLog:{create:jest.fn()}};const db:any={personnelAction:{findMany:jest.fn().mockResolvedValue([action])},$transaction:jest.fn(async(fn:any)=>fn(tx))};return {service:new PersonnelEffectsService(db),tx,db};}
 const base={id:'decision',status:'APPROVED',type:'RESIGNATION',subjectId:'employee',requestedById:'hr',decidedById:'director',appliedAt:null,payload:{},effectiveAt:today};
 it('does not apply a future decision even if fetched by a stale worker',async()=>{const {service,tx}=setup({...base,effectiveAt:new Date('2026-11-01')});await service.applyDue(today);expect(tx.user.update).not.toHaveBeenCalled();expect(tx.auditLog.create).not.toHaveBeenCalled();});
 it('does not replay a decision already applied by another worker',async()=>{const {service,tx}=setup({...base,appliedAt:new Date()});await service.applyDue(today);expect(tx.user.update).not.toHaveBeenCalled();});
 it('revokes account, sessions and face templates together on resignation date',async()=>{const {service,tx}=setup(base);await service.applyDue(today);expect(tx.user.update).toHaveBeenCalledWith({where:{id:'employee'},data:{employmentStatus:'RESIGNED',status:'DISABLED'}});expect(tx.refreshToken.updateMany).toHaveBeenCalled();expect(tx.faceEmbedding.updateMany).toHaveBeenCalled();expect(tx.contract.updateMany).toHaveBeenCalled();expect(tx.personnelAction.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:{id:'decision',appliedAt:null,status:'APPROVED'}}));});
});
