 'use client';
import React, { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, errorMessage } from '@/lib/api';
import { useAuthStore } from '@/lib/auth-store';
import { Button, Input, Label, Select, Textarea } from '@/components/ui/primitives';
import { useToast } from '@/components/ui/toaster';

type Row = Record<string, any>;
const names: Record<string,string> = {REQUESTED:'Đề nghị mượn',APPROVED:'Đã duyệt',BORROWED:'Đang mượn',RETURN_REQUESTED:'Đề nghị trả',RETURNED:'Đã trả',REJECTED:'Từ chối',SUBMITTED:'Quản lý đã đánh giá',HR_VERIFIED:'HR đã thẩm định',PENDING_REVIEW:'Chờ thẩm định',REVIEWED:'Đã thẩm định',CLOSED:'Đã đóng',FINALIZED:'Đã chốt',OPEN:'Đang mở'};
export default function HrWorkflowsPage() {
 const user=useAuthStore(s=>s.user); const roles=user?.roles??[]; const hr=roles.some(r=>['ADMIN','KM_MANAGER','HR_CB'].includes(r)); const bod=roles.some(r=>['ADMIN','BOD'].includes(r));
 const finance=roles.some(r=>['ADMIN','ACCOUNTANT'].includes(r)); const recruiter=roles.some(r=>['ADMIN','KM_MANAGER','HR_RECRUITER'].includes(r)); const manager=roles.includes('LINE_MANAGER');
 const qc=useQueryClient(), toast=useToast(); const [busy,setBusy]=useState(false); const [tab,setTab]=useState('loans');
 const useRows=(key:string,url:string,enabled=true)=>useQuery<Row[]>({queryKey:[key],queryFn:async()=>(await api.get(url)).data,enabled});
 const me=useQuery<Row>({queryKey:['workflow-me'],queryFn:async()=>(await api.get('/auth/me')).data});
 const corrections=useRows('workflow-corrections',hr?'/hrms/attendance-regularizations':'/hrms/attendance-regularizations/my');
 const loans=useRows('physical-loans','/hr-workflows/record-loans'); const probation=useRows('probation-reviews','/hr-workflows/probation');
 const req=useRows('requisitions','/recruitment/requisitions',recruiter||finance||bod||manager); const periods=useRows('attendance-periods','/attendance-periods',hr||finance);
 const tasks=useRows('onboarding-tasks','/hrms/lifecycle/onboarding-tasks');
 const employees=useQuery<Row[]>({queryKey:['workflow-employees'],queryFn:async()=>(await api.get('/employees')).data,enabled:hr||manager});
 const orgs=useRows('workflow-orgs','/org-units',recruiter||hr||manager);
 async function act(url:string,body:Row={},method='post') { setBusy(true); try {await api.request({url,method,data:body,timeout:180000}); await qc.invalidateQueries(); toast('Đã cập nhật quy trình','success');} catch(e){toast(errorMessage(e),'error');} finally{setBusy(false);} }
 function values(e:React.FormEvent<HTMLFormElement>){e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,string>;}
 const cls='rounded-lg border p-4 space-y-3'; const field='space-y-1';
 return <div className="space-y-5"><h1 className="text-2xl font-semibold">Quy trình & xác nhận</h1><p className="text-sm text-muted-foreground">Mỗi bước ghi nhận người thực hiện. Phê duyệt phải độc lập với người đề xuất; quyết định nhân sự áp dụng theo ngày hiệu lực.</p>
 <div className="flex flex-wrap gap-2">{[['correction','Giải trình công'],['bank','Ngân hàng & thuế'],['loans','Mượn hồ sơ gốc'],['probation','Thử việc'],['onboarding','Hội nhập'],...((recruiter||finance||bod||manager)?[['requisition','Chỉ tiêu tuyển dụng']]:[]),...((hr||finance)?[['attendance','Chốt công']]:[])].map(([id,name])=><Button key={id} variant={tab===id?'default':'outline'} onClick={()=>setTab(id)}>{name}</Button>)}</div>
 {tab==='bank'&&<form className={cls} onSubmit={e=>{const v=values(e);const changes:Row={};for(const [k,label] of [['bankAccount','Số tài khoản'],['bankName','Ngân hàng'],['taxDependentCount','Người phụ thuộc']]){const newValue=k==='taxDependentCount'?Number(v[k]):v[k];if(String(newValue)!==String(me.data?.[k]??''))changes[k]={label,oldValue:me.data?.[k]??null,newValue,tier:2};}void act('/profile-change-requests',{changes,reason:v.reason,attachmentUrls:[v.proof]});}}><h2 className="font-medium">Đề nghị xác minh ngân hàng và người phụ thuộc</h2><p className="text-sm">HR xét duyệt tại trang Đề xuất hồ sơ. Bảng lương chụp thông tin đã được xác minh tại thời điểm tính.</p><label>Số tài khoản<Input name="bankAccount" defaultValue={me.data?.bankAccount??''} required/></label><label>Ngân hàng<Input name="bankName" defaultValue={me.data?.bankName??''} required/></label><label>Số người phụ thuộc<Input name="taxDependentCount" type="number" min={0} max={30} defaultValue={me.data?.taxDependentCount??0} required/></label><label>Lý do<Input name="reason" minLength={5} required/></label><label>Đường dẫn minh chứng<Input name="proof" required/></label><Button disabled={busy}>Gửi HR xác minh</Button></form>}
 {tab==='correction'&&<><form className={cls} onSubmit={e=>{const v=values(e);void act('/hrms/attendance-regularizations',{...v,userId:user?.id,employeeName:user?.fullName??'',requestedCheckIn:v.requestedCheckIn||undefined,requestedCheckOut:v.requestedCheckOut||undefined});}}><h2 className="font-medium">Đề nghị bổ sung công của mình</h2><div className="grid sm:grid-cols-2 gap-3"><label>Ngày làm việc<Input name="workDate" type="date" required/></label><label>Giờ vào<Input name="requestedCheckIn" type="time"/></label><label>Giờ ra<Input name="requestedCheckOut" type="time"/></label><label>Lý do và minh chứng<Textarea name="reason" minLength={5} required/></label></div><Button disabled={busy}>Gửi giải trình</Button></form>{corrections.data?.map(c=><div className={cls} key={c.id}><p>{c.employeeName} · {c.workDate?.slice(0,10)} · {c.status}</p><p>{c.requestedCheckIn??'Chưa cập nhật'} → {c.requestedCheckOut??'Chưa cập nhật'} · {c.reason}</p>{hr&&c.status==='PENDING'&&c.userId!==user?.id&&<div className="flex gap-2">{['APPROVED','REJECTED'].map(status=><Button key={status} disabled={busy} variant={status==='APPROVED'?'default':'outline'} onClick={()=>{const decisionNote=prompt('Kết quả xác minh / lý do từ chối');if(decisionNote)void act(`/hrms/attendance-regularizations/${c.id}/decide`,{status,decisionNote},'patch');}}>{status==='APPROVED'?'Duyệt công':'Từ chối'}</Button>)}</div>}</div>)}</>}
 {tab==='loans'&&<><form className={cls} onSubmit={e=>{const v=values(e); void act('/hr-workflows/record-loans',v);}}><h2 className="font-medium">Đề nghị mượn bản gốc của mình</h2><div className="grid sm:grid-cols-2 gap-3"><label className={field}>Mã hồ sơ<Input name="itemKey" required/></label><label className={field}>Tên bản gốc<Input name="itemDescription" minLength={5} required/></label><label className={field}>Hạn trả<Input name="dueDate" type="date" required/></label><label className={field}>Lý do<Input name="reason" minLength={5} required/></label></div><Button disabled={busy}>Gửi đề nghị</Button></form>{loans.isError&&<p>Không tải được hồ sơ: {errorMessage(loans.error)}</p>}{loans.data?.map(l=><div className={cls} key={l.id}><p className="font-medium">{l.itemDescription} — {names[l.status]??l.status}</p><p className="text-sm">{l.reason} · Hạn trả {l.dueDate?.slice(0,10)}</p><div className="flex gap-2">{hr&&l.userId!==user?.id&&l.status==='REQUESTED'&&<><Button disabled={busy} onClick={()=>act(`/hr-workflows/record-loans/${l.id}`,{status:'APPROVED'},'patch')}>Duyệt</Button><Button variant="outline" disabled={busy} onClick={()=>act(`/hr-workflows/record-loans/${l.id}`,{status:'REJECTED'},'patch')}>Từ chối</Button></>}{hr&&l.userId!==user?.id&&['APPROVED','RETURN_REQUESTED'].includes(l.status)&&<Button disabled={busy} onClick={()=>{const proof=prompt('Đường dẫn biên bản giao nhận');if(proof)void act(`/hr-workflows/record-loans/${l.id}`,{status:l.status==='APPROVED'?'BORROWED':'RETURNED',evidenceUrl:proof},'patch');}}>Xác nhận {l.status==='APPROVED'?'giao bản gốc':'đã nhận lại'}</Button>}{l.userId===user?.id&&l.status==='BORROWED'&&<Button disabled={busy} onClick={()=>act(`/hr-workflows/record-loans/${l.id}`,{status:'RETURN_REQUESTED'},'patch')}>Đề nghị trả</Button>}</div></div>)}</>}
 {tab==='probation'&&<>{(hr||manager)&&<form className={cls} onSubmit={e=>{const v=values(e);void act('/hr-workflows/probation',{...v,score:Number(v.score),contractSalary:Number(v.contractSalary),contractEndDate:v.contractEndDate||undefined});}}><h2 className="font-medium">Quản lý đánh giá kết quả thử việc</h2><div className="grid sm:grid-cols-2 gap-3"><label>Nhân viên<Select name="userId" required><option value="">Chọn nhân viên</option>{employees.data?.filter(u=>u.employmentStatus==='PROBATION').map(u=><option key={u.id} value={u.id}>{u.fullName}</option>)}</Select></label><label>Điểm<Input name="score" type="number" min={0} max={100} required/></label><label>Kết luận<Select name="recommendation"><option value="PASS">Đạt</option><option value="FAIL">Không đạt</option></Select></label><label>Lương chính thức<Input name="contractSalary" type="number" min={1} required/></label><label>Hợp đồng<Select name="contractType"><option value="FIXED_TERM">Có thời hạn</option><option value="INDEFINITE">Không thời hạn</option></Select></label><label>Ngày hiệu lực<Input name="effectiveDate" type="date" required/></label><label>Ngày kết thúc (nếu có thời hạn)<Input name="contractEndDate" type="date"/></label><label>Minh chứng<Input name="evidenceUrl" required/></label></div><label>Nhận xét<Textarea name="assessment" minLength={10} required/></label><Button disabled={busy}>Gửi HR thẩm định</Button></form>}{probation.data?.map(p=><div className={cls} key={p.id}><p className="font-medium">{employees.data?.find(u=>u.id===p.userId)?.fullName??'Đánh giá thử việc'} — {names[p.status]??p.status}</p><p>{p.score}/100 · {p.assessment}</p><p className="text-sm">Hiệu lực: {p.effectiveDate?.slice(0,10)}</p>{((hr&&p.status==='SUBMITTED')||(bod&&p.status==='HR_VERIFIED'))&&<div className="flex gap-2">{(p.status==='SUBMITTED'||p.recommendation==='PASS')&&<Button disabled={busy} onClick={()=>{const note=prompt('Ghi chú thẩm định / phê duyệt');if(note)void act(`/hr-workflows/probation/${p.id}`,{status:p.status==='SUBMITTED'?'HR_VERIFIED':'APPROVED',note},'patch');}}>{p.status==='SUBMITTED'?'HR xác minh':'Duyệt ký chính thức'}</Button>}{p.status==='HR_VERIFIED'&&<Button variant="outline" onClick={()=>{const note=prompt('Lý do không ký chính thức');if(note)void act(`/hr-workflows/probation/${p.id}`,{status:'REJECTED',note},'patch');}}>Không ký chính thức</Button>}</div>}</div>)}</>}
 {tab==='onboarding'&&<><p className="text-sm">IT đặt mật khẩu và kích hoạt tài khoản tại trang Quản trị người dùng trước khi xác nhận. HR, hành chính và quản lý xác nhận phần việc của mình.</p>{tasks.data?.map(t=><div key={t.id} className={cls}><p>{t.employeeName} · {t.category}</p><p className="font-medium">{t.title}</p><p>{t.isCompleted?'Đã xác nhận':'Chờ xác nhận'}</p>{!t.isCompleted&&t.userId!==user?.id&&<Button disabled={busy} onClick={()=>act(`/hrms/lifecycle/onboarding-tasks/${t.id}/toggle`,{},'patch')}>Xác nhận hoàn thành</Button>}</div>)}</>}
 {tab==='requisition'&&<><form className={cls} onSubmit={e=>{const v=values(e);void act('/recruitment/requisitions',{...v,headcount:Number(v.headcount),budgetMonthly:Number(v.budgetMonthly),orgUnitId:v.orgUnitId||undefined});}}><h2 className="font-medium">Đề nghị chỉ tiêu và ngân sách</h2><div className="grid sm:grid-cols-2 gap-3"><label>Tên đề nghị<Input name="title" required/></label><label>Vị trí<Input name="position" required/></label><label>Số lượng<Input name="headcount" type="number" min={1} required/></label><label>Tổng ngân sách lương / tháng<Input name="budgetMonthly" type="number" min={1} required/></label><label>Đơn vị<Select name="orgUnitId" required><option value="">Chọn đơn vị</option>{orgs.data?.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></label><label>Lý do<Input name="reason" required/></label></div><Button disabled={busy}>Gửi thẩm định</Button></form>{req.data?.map(q=><div key={q.id} className={cls}><p className="font-medium">{q.title} — {names[q.status]??q.status}</p><p>{q.position} · {q.headcount} người · {q.budgetMonthly?.toLocaleString('vi-VN')} đ/tháng</p><div className="flex gap-2">{q.status==='PENDING_REVIEW'&&q.requestedById!==user?.id&&<>{recruiter&&!q.hrAssessedBy&&<Button disabled={busy} onClick={()=>{const note=prompt('Kết quả thẩm định nhu cầu');if(note)void act(`/recruitment/requisitions/${q.id}/assess`,{kind:'HR',note});}}>HR thẩm định</Button>}{finance&&!q.financeAssessedBy&&<Button disabled={busy} onClick={()=>{const note=prompt('Kết quả thẩm định ngân sách');if(note)void act(`/recruitment/requisitions/${q.id}/assess`,{kind:'FINANCE',note});}}>Tài chính thẩm định</Button>}</>}{q.status==='REVIEWED'&&bod&&<Button disabled={busy} onClick={()=>act(`/recruitment/requisitions/${q.id}/approve`)}>Giám đốc phê duyệt</Button>}</div></div>)}</>}
 {tab==='attendance'&&<><form className={cls} onSubmit={e=>{const v=values(e);void act('/attendance-periods/finalize',{month:Number(v.month),year:Number(v.year)});}}><h2 className="font-medium">Chốt công tháng đã kết thúc</h2><p className="text-sm">Xử lý đơn giải trình và ngày thiếu cặp vào–ra trước khi chốt. Bảng lương lấy bản công đã chốt.</p><div className="flex gap-3"><label>Tháng<Input name="month" type="number" min={1} max={12} required/></label><label>Năm<Input name="year" type="number" min={2000} max={2100} defaultValue={new Date().getFullYear()} required/></label></div><Button disabled={busy}>Kiểm tra & chốt công</Button></form>{periods.data?.map(p=><div className={cls} key={p.id}><p>Tháng {p.month}/{p.year} — {names[p.status]??p.status} · phiên bản {p.version}</p>{hr&&p.status==='FINALIZED'&&<Button disabled={busy} variant="outline" onClick={()=>{const reason=prompt('Lý do mở lại công (ít nhất 5 ký tự)');if(reason)void act(`/attendance-periods/${p.id}/reopen`,{reason});}}>Mở lại để điều chỉnh</Button>}</div>)}</>}
 </div>;
}
